### ISSUE TITLE
Board picker dialog doesn't initialize correctly if boards are currently deluxe-size

### ISSUE THREAD

**Issue by pacman-ghost** [vasl-developers/vasl#1062]
To repro, create a new map with a board using deluxe-size hexes. Once the main window has come up, choose "Pick new boards for this scenario." The dialog comes up with the "Deluxe-size hexes" checkbox cleared, and the board rendered at normal size.

Clicking on the checkbox does nothing.

Clicking on the checkbox again (to now clear it) renders the board at a tiny size.

VASSAL 3.5.5 + VASL 6.6.2, Windows 10

**Comment by derimmer** [comment]
Tested this today with my current beta build of vasl6.6.4 and vassal3.6.6. All worked properly.

When I opened Pick New Boards for this scenario, the dialogue came up with the Deluxe-size hexes checkbox cleared and the board rendered at Deluxe size. If I picked a new board; it showed up as regular size. If I clicked the checkbox, it increased to deluxe size and stayed that way if I clicked ok to close the dialog and return to the game window.

Whatever was causing the problem seems to have been fixed in the interim (could have been something in VASSAL between 3.5.5 and 3.6.3. 

Am going to close the issue.
