### ISSUE TITLE
Overlays are not resizing correctly when switching between normal- and deluxe-size hexes

### ISSUE THREAD

**Issue by pacman-ghost** [vasl-developers/vasl#1063]
Somebody reported this working for them here:
	http://www.gamesquad.com/forums/index.php?threads/changing-the-size-ratio-between-counters-and-the-map.166892/post-2080494

but it didn't for me when I tried it.

Example attached: [zoom-test.zip](https://github.com/vasl-developers/vasl/files/7842838/zoom-test.zip)

VASSAL 3.5.5 + VASL 6.6.2, Windows 10

**Comment by derimmer** [comment]
I have done some testing on this and it appears to me that things are working properly. 

When changing the size of a board by checking or clearing the "Deluxe-size hexes" checkbox, overlays match the degree of magnification of the board they are on. 

Using your zoom-test.vsav, PMG I discovered that you were using a regular board and a deluxe overlay (dx1) and I believe that was causing the mismatch as you moved back and forth. 

As well, my testing only covered overlays added via boardpicker. I have not yet tried this with overlays from the draggable overlay extension. I suspect that, since those overlays are actually counters, they will not toogle in size when using the "Deluxe-hex size" checkbox just as regular counters do not. PMG, would you have placed the dx1 overlay using the draggable overlays?

There is a whole lot of other stuff going on in the GS thread you posted and I haven't tried to sort any of that out. I was just testing the behaviour of overlays.
