### ISSUE TITLE
LOS thread confused by transform of hill to grain

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#1141]
vasl version 6.6.3, vassal 3.5.8, linux os

In J94 Kempf at Melikhovo all hill depictions are transformed to ground level grain. The LOS thread does not identify woods in the grain as an obstacle.

Steps to reproduce:
Start a new game. Select board 3. Terrain SSR. Transformations. "All Level 1 is Grain," "All Level 2 is grain." Apply. Done. Ok. 

[As an aside, the applied transformations disappear from the dialog when applied. I don't know if this is expected behavior or not.]

LOS traced from 3V3 to 3X4 shows as clear
![transform hill to grain 1](https://user-images.githubusercontent.com/7386638/161801698-e2e73c2a-544d-4c3d-8398-e91686ff744b.jpg)
Oddly LOS traced to the back corner of 3W4 shows as blocked:
![transform hill to grain 2](https://user-images.githubusercontent.com/7386638/161802362-cc552a2c-b10b-488b-a950-ba5626a1067e.jpg)

**Comment by derimmer** [comment]
There is a broader issue here which is that terrain transformations and los checking are two separate things, which sometimes work together and sometimes don't. Clearly in this instance they don't. 

Given the large number of permutations and combinations of terrain transformations, it is not useful to try and "fix" this broader issue all at once. I think we will have much more success (and more importantly, fewer unintended consequences) if we handle these one-by-one. 

So it is very useful for @jrvjrv and anyone else to flag these whenever they run across them.  

Related to this is the work that I have started on overlays and having them work with los. In 6.6.4 I began with some of the simple, single-terrain overlays (grain, brush, open ground, etc). 

With other overlays you will continue to get the red line around the overlay and a message saying "los disabled while crossing the overlay". For terrain transformations you will just get wacky los results such as the ones @jrvjrv posted. I don't think I can add a warning message similar to overlays because I can't tell which transforms work with los and which don't.

**Comment by derimmer** [comment]
Working on this now. 
@jrvjrv one thing: in this instance you do not have the LOSH colour set for your los thread. If you had, you would have seen a grain hindrance in W4 as is shown in the target hex text box. 

The level1 and 2 to grain transformation is working. If I string los elsewhere on the board where the transformation happens, it works. What is not working are the Level1 hexes with trees. The transformation sets every pixel at level 1 or 2 to grain without checking to see if there is other terrain besides OG. I will see if I can fix that. 

The reason that the los to the vertex shows blocked is that it just happens to hit a tree pixel in W4 that is at level 0 and therefore was not changed to grain by the transformation.

**Comment by derimmer** [comment]
@jrvjrv The bug I fixed related to a Level to Terrain transformation. 

What I did not fix was the special overlay for J94. Using that overlay does not trigger any los adjustments. I am working on los and overlays but that is going to be a long journey.
