### ISSUE TITLE
LOS engine ignores Smoke

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#1179]
board 60, orchards out-of-season, level 2 +2 Smoke in 60G4, LOS from 60J5 to 60C2 is given as +1 hindrance.
![vasl-smoke-problem](https://user-images.githubusercontent.com/7386638/175133406-15dc9845-0bef-4c41-ba06-9f64872a8e25.png)

If you move the Smoke to other hexes, e.g. 60H4 or 60F3, the hindrance is shown as the correct +3. My first thought is that the building in 60G4 is somehow confusing vasl, but I have made no attempt to verify this.

**Comment by scottf2** [comment]
Experimented with this a bit (JR submitted the ticket based on a post I made on the ASL Discord). It doesn't seem to be building related, but maybe range? IE: the smoke seems to stop registering as a hindrance at greater than 3 hex range (from the smoke).

**Comment by derimmer** [comment]
I had commented on this previously but the comment has disappeared. 

Anyway, I agree that there is a bug.  

@davidsullivan317 The code that handles this is the checkHexSmokeRule() method which in turn calls isBlindHex(). The key line of code in isBlindHex() is:

`return rangeToTarget <= Math.max(2 * (groundLevel + terrainHeight+ terrainHeightadj) + (rangeToSource / 5) - sourceElevation - targetElevation + 1, 1);'

In the example shown above, 

rangeToTarget = 4
groundLevel=0  - base level of hex containing the obstacle/hindrance
terrainHeight=2  - height of the obstacle/hindrance
terrainHeightadj=0
rangeToSource=3
sourceElevation =2
targetElevation=1

Thus 

return 4<= Math.max(2 * (0 + 2 + 0) + 3/5 -2 -0 +1, 1)
return 4 <= Math.max (4 +0.6 -1, 1)
return 4 <= Math.max (3.6,1)
return false

If the rangeToTarget is <= 3 then this routine will return true and the Hindrance will apply as @jrvjrv and @scottf2 have shown/stated. 

This test works properly when the terrainHeight is that of an obstacle because it is only called in situations where one of sourceElevation or targetElevation is above terrainHeight and one of them is below terrainHeight. In cases, where either is equal to terrainHeight other routines handle the LOS test and isBlindHex is never called. So, we have a bug when isBlindHex() is called to determine if a LOSH applies.

**Comment by derimmer** [comment]
Thanks to @davidsullivan317, I have found a solution to this. The blind hex test is meant to work with LOS checks where one of the target or source elevation is above the terrainHeight and the other is below. It is not meant to be called when target or source elevation = terrainHeight. It was being called mistakenly from checkHexSmokeRule(). I have fixed the code in that method. This fix will be in 6.6.5.
