### ISSUE TITLE
Counter changes: movement trail, Scheurzen, Non-Emplaced

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1280]
This implements 3 changes to counters:

For vehicles with Scheurzen, it adds a menu item/keystroke to display a red Sz on the counter

For guns, it adds a menu item/keystroke to place a "Non-emplaced" counter on the gun

For infantry and vehicles, it adds a movement trail menu item/keystroke

**Comment by derimmer** [comment]
This first commit has a few missing pieces that will be pushed shortly

The huGun prototype does not contain the NON-emplaced marker

Swedish leaders do not contain the movement trail trait 

Some Chicom SMC do not contain the movement trail trait

The implementation of the movement trait requires that the Chinese Dare-Death be implemented different. This has not been added yet. 

Wagons do not yet implement the movement trail trait.

**Comment by apbills** [comment]
Damn, I missed a lot.  Do you want me to update the extension and resend to you?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by derimmer** [comment]
@apbills was just sending you and email. Will do it here instead:

I have pushed up 90% of the changes. there are a few bits and pieces still to be done. If they don't make the beta version that is not a worry. They will all be done before the official release. 

Took my time with this to make sure I did it right - not just in terms of these changes but also in preserving the ability to update counters from older versions to the new ones. That was tricky and made for some laborious work. But it is done. 

Great job doing this. 

I will look after wagons; I just ran out of gas to today. And I wanted to push up what I had done because it all gets done as changes to the buildFile in VASL and that happens as an overwrite of the whole file and not as a merge. So best to get it done before someone else adds a change to the buildFile and something gets overwritten. 

If you can send me a revised extension dealing with the huGun, the swedish leaders and the two Chi com SMC besides the hero and leaders (one is the Comm Guerrila hero; the other is a 1-0-9 or something like that), that would be great.

I will look after the Dare Death stuff. You have done it; but I need to think about how to merge it in.

**Comment by apbills** [comment]
OK, will work it this afternoon and get an update to you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by apbills** [comment]
See below.  This extension is version 0.2.


  1.  huGun. Completed in version 0.1
  2.  Swedish leaders.  I see why this was missed, although I should have seen it earlier.  For some reason they use prototype svLDR, not svLDR1 (which doesn’t exist).  All other nationalities use xxLDR1.  Not sure if you want to make this consistent. I have updated svLDR.
  3.  ChiCom SMC.  I found the North Korean suicide SMC and the North Korean Communist Guerilla hero.  I think those are what you were referring to as I do not find any issue with the ChiCom units.  From a consistency standpoint, the NK Communist guerilla, Swedish, and Russian partisan SMC tabs should place the hero first like all the other tabs, they currently have the hero after the other leaders.
  4.  I found I missed the German NSDAP leaders, all of the geGES, ssGES and the geLDR, ssLDR prototypes.  I’m not sure what product these come from, but they are now updated.

One thing about my process on this.  I was using the Search function to find each prototype I needed to duplicate and modify.  In the case of the leaders I searched for LDR1 and then cycled through them all, which is why I missed the Swedes (although clearly I missed the huGUN prototype even though I was searching for GUN).  Is there a “Where used” type function in the editor?  That would come in handy when making these kind of modifications.

Alan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by derimmer** [comment]
Everything done but Wagons and reordering a few panels

**Comment by apbills** [comment]
Doug,
I just realized I did not add Schuerzen to the SS colored vehicles, just to the Wehrmacht ones.  I have a white overlay made up.  Do you want me to make up an extension with the SS vehicles, or maybe just mod the beta vmod and send back to you.  Let me know.

Alan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by derimmer** [comment]
Mod the beta mod and send her back.

**Comment by derimmer** [comment]
Schuerzen added to SS. Closing again

**Comment by apbills** [comment]
Doug,
Did you bring in the updated SS vehicles are just use the .vmod I sent you with them in it?  When I test the just released version of the 6.6.6beta the SS vehicles don’t have the Schuerzen overlay in the module.  I have attached that .gif file to this e-mail, not sure why it did not make it into the version you released.

***@***.***

Alan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by derimmer** [comment]
It appears that I can't copy-paste worth shit. When I add the two ssSz images properly everything works. I will update the link on VASL.info to point to the updated beta file. Should be operative in 30 minutes.
