### ISSUE TITLE
Add Concealment UI improvement for stacks

### ISSUE THREAD

**Issue by jvarsoke** [vasl-developers/vasl#148]
More sensible concealment user interface - when you have a whole stack selected and hit CTRL-C to conceal, only one ? counter should be on top, and the rest of the stack should be concealed under it. Right now, everyone gets their own ? marker -- which is never what you would do over the board. Similarly, selecting a whole stack and unconsealing should eliminate all ? markers, while selecting only one counter could unconceal and bubble up to the top above the ? marker. If this was the only counter in the stack then the ? should be deleted.

**Comment by ramisaa** [comment]
As this is, for me, the most uncomfortable feature of VASL I actually went and had a look at the code. After a very quick look I was left with the impression that the stack counters are processed individually without a regard of the other counters in the selection (well actually it would be other selected counters in the hex as the selection can span multiple "hexes") and that the functionality is triggered by VASSAL itself. Do you, VASL developers, have any insight on this? Would it even be possible to implement? I am asking because if it is, I could perhaps have a deeper look into it.

**Comment by derimmer** [comment]
In regard to the original post, most VASL players have discovered that right clicking the top unit of a stack and then selecting conceal from the pop up menu will produce the desired result: one ? on top of the stack and all the units below it concealed. Deleting the ? counter unconceals the entire stack. 

Personally, I don't think there is an issue here. 

As for your observations about how VASL/VASSAL works, I am not entirely sure. Certainly, stacking is  managed by VASSAL.

**Comment by ramisaa** [comment]
Oh, it might be so! I have always selected the units that I want to conceal. Thanks!

**Comment by derimmer** [comment]
Closing. Nothing to see here. Move on.
