### ISSUE TITLE
countermetadata bug

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1493]
VASSAL Bug report 2700  https://github.com/vassalengine/modules/issues/2700

**Comment by apbills** [comment]
I looked at the error log attached to the original vassal error report.  The error occurred as a saved file (Documents (Mobile Sync)\VASL\saves\S1 Retaking Vierville\S1 Retaking Vierville American Setup.vsav) was loaded from what may have been a cloud storage area (based on the "Mobile Sync" path).  Multiple network errors are listed, dice images (DC5_W.png, DC1_W.png) could not be found.  This was using 3.6.19/6.6.6.  I don't know how this can even be tracked down and unless this occurs regularly in 3.7+/6.6.7+ it is not clear if the CounterMetadataFile was corrupted as part of the network errors, however, we have not seen any issues with the metadata that I know of, so I suspect the error was a one off type thing.

I would say that with the increase in users using cloud storage it may be useful to add in some exception processing when something like this occurs (as well as encouraging users to not load files directly from the cloud), however, it is not clear if the effort to do that really adds anything if my suspicions are correct about the network load.

**Comment by zgrose** [comment]
Better to add resiliency to the app than to force users back to the 90s, IMO...

**Comment by apbills** [comment]
I have not found anything that indicates what the user experience was other than what is in the errorlog.  maybe somethign else is in there that I don't understand (there is a lot I don't understand).  It clearly hasn't forced them back to the 90s.  What is obvious is that there is nothing specific in the CounterMetadataFile that needs fixing, i.e., the bug is not attributable to that file as published.  If there was every user would be getting this error. all the time.

Maybe there is some value in providing the user with feedback, although other than adding some kind of retry loop, I don't have the knowledge to understand what beyond "A network error occurred.  Please check your network connectivity and try again." can be done.

**Comment by zgrose** [comment]
I was referring to the idea of "encouraging users to not load files directly from the cloud" as a regression.

As to the best solution for not being able to read out of the vmod, I'm not sure. Since it's old code, it may be all moot, but it's this section that's puzzling to me w/o stepping code (below). It looks like xerces is reading something and that's what failed.

<img width="821" alt="Screenshot 2024-01-29 143414" src="https://github.com/vasl-developers/vasl/assets/5044847/bbe11794-d76f-4ffe-b6ff-419e92c3fc79">

**Comment by derimmer** [comment]
For some reason (and this can often be due to conditions outside of VASL and difficult to replicate), an I/O error is occurring in CounterMetadataFile.java. 

This i/o error is being trapped but the action taken when it occurs is to cause a bug report. It seems to me that it might be more useful to (1) disable LOS checking; and (2) notify the user. This takes place in the CounterMetadataFile.java constructor method which I think needs to be reworked. 

Thanks for your comments on this guys. I can work on it from here.

**Comment by derimmer** [comment]
I have replaced the Exception.bug() with a warning message. The game will continue to run but the user is made aware of a problem.
