### ISSUE TITLE
Persist night/dust/ other? settings in .vsav/.vlog files

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1515]

**Comment by derimmer** [comment]
Beyond night and dust are there other settings that should persist from game session to game session?

**Comment by derimmer** [comment]
Testing with 668beta7, if special dust is selected from a the toolbar button, that checks the special dust preference and the setting persists. 

If the special dust preference is selected it ONLY persists special dust if it is selected from the toolbar button and does not persist any of the other dust levels.

**Comment by derimmer** [comment]
I asked over at VASSAL about this and was directed to the Scenario Options item on the File menu. Apparently, according to the Reference Manual this should be helpful in our situation. 

However, it is always greyed out on my device and the instructions in the Ref manual are not unlocking it. Seeking help from VASSAL. But we might have a path to some interesting things here.

**Comment by derimmer** [comment]
The Scenario Options feature is a good one. Finally got it to work. 

BUT, I don't think it is going to help with the the persistence of NIght and other LV which are built on the VASSAL Shader class. This class appears to contain a "startsOn" property which must be set to true or false. This property is checked at start up and applied. I have not been able to get the Scenario Options or any other feature to override this setting, I have posted about this on VASSAL but no response yet.

**Comment by zgrose** [comment]
Are you sure it's the `startsOn` property that's the issue. In the night shader, I see you initialize the base class and then set visibility off?

<img width="541" alt="Screenshot 2024-08-09 103301" src="https://github.com/user-attachments/assets/1754bd30-92fe-4bcd-9fee-fbb35ef43758">

**Comment by derimmer** [comment]
Well, I am never entirely sure of anything when it comes to coding. But, in this case yes, I believe startsOn is the problem. 

Even if I take those two lines of code out of ASLNightMapShader, at some point VASSAL's NightMaderShader gets called and it is ALWAYS going to give startsOn a true or false value. If it finds startsON == null then it will change it to False, so not initializing startsOn is not a solution.

**Comment by zgrose** [comment]
`toggleShading` does this:
````
protected void toggleShading() {
        this.setShadingVisibility(!this.shadingVisible);
    }
````
`draw` does this:
```
if (this.shadingVisible) {
````

It doesn't matter, best I can tell, if it startsOn or not, because you're literally turning off the draw.

Comment out line 11, ie. `//shadingVisible = false;` and I bet the shaders will show according to their saved values.

**Comment by zgrose** [comment]
If you want, I can prep a Pull Request with one of more of these changes in place, but I'm not setting really well for actually running and testing it. But I can certainly do the code wrangling for you if you want to run with my best guess in place.

**Comment by zgrose** [comment]
OK. Nevermind the above. The shader is getting initialized before the scenario is even loaded and there are various calls to reset so that line 11 actually does nothing, so we're probably both chasing red-herrings. Setting startsOn in the constructor/initialization just would mean it starts on regardless of whether the button was clicked... 

Digging some more to find the correct moment in the scenario load to toggle it one based on the context of the property in the save file (if there is a property in the save file...).

**Comment by derimmer** [comment]
> Digging some more to find the correct moment in the scenario load to toggle it one based on the context of the property in the save file (if there is a property in the save file...).

Thanks. I think the whole point of the Scenario Options properties is to add something to the save file that doesn't exist now. That could easily be a boolean on/off property. I can create the element that sets such a property but I can't figure out how to use that property when opening a saved game. Which is what we need for persistence.

**Comment by zgrose** [comment]
Well, I believe I have the answer for you.... :)

The correct place *seems* to be `ScenInfo.setState()`
The shaders are sub-components on the `ASLMap` component. So the trick is to just extend `ScenInfo` with new properties (on/off for each shader) and then just set the shaders at the end of `setState()`

As a proof-of-concept I dropped this in at the end of setState:

````
    Iterator<ASLMap> mapIterator = GameModule.getGameModule().getComponentsOf(ASLMap.class).iterator();
    if (mapIterator.hasNext()) {
      ASLMap map = mapIterator.next();
      this.trySetShaderVisibility(map, ASLNightMapShader.class, true);
      this.trySetShaderVisibility(map, ASLDTODustMapShader.class, false);
      this.trySetShaderVisibility(map, ASLFogMapShader.class, false);
      this.trySetShaderVisibility(map, ASLHeatHazeMapShader.class, false);
      this.trySetShaderVisibility(map, ASLLVMapShader.class, false);
      this.trySetShaderVisibility(map, ASLSunBlindnessMapShader.class, false);
    }
````

and added a private helper:

````
private <T> void trySetShaderVisibility(ASLMap map, Class<T> shader, boolean value) {
    Iterator<T> shaderIterator = map.getComponentsOf(shader).iterator();
    if (!shaderIterator.hasNext()) return;
    try {
      MapShader shaderObj = (MapShader) shaderIterator.next();
      shaderObj.setShadingVisibility(value);
    } catch (Exception e) {
      String message = "The scenario attempted to set visibility on " + shader.getName() + " but it is not of type MapShader. No user action required.";
      ErrorDialog.dataWarning(new BadDataReport(message, shader.getName()));
    }
  }
````

And my test game opens with the shader active.

So the final piece of the puzzle is to set the flag on ScenInfo based on the shader activation.....

BUT....

I have a feeling that the Shader is a per-user setting so you're only going to see the Shader if you turned it on.
Which I suppose is a step better than before, but maybe not the end-goal.

**Comment by derimmer** [comment]
Damn, you're a genius (either that or I am just a fuckin' idiot). I have been trying to think of a place in the existing code where values from a Saved Game are loaded. Snipers never occurred to me! Duh!

This is certainly a clear proof-of-concept. Not entirely a 100% solution yet. If I save a game with Night on and close it, then open a new game, the new game will have night on. I think a new game should always default to off. If I turn it off and reopen my saved game, Night will be on. That is what we want.

If I close a game with Night On and open a saved game which had Night Off, Night stays on. So, I need to sort that. 

But I suspect that these are things that your PoC didn't try to cover. I will see what I can add to handle the various permutations. 

But, mainly, a big thanks for this. Not only does it address the specific issue but it shows me how to get at Saved Game details and manipulate them - which is a big gain. 

I will also look at the multi-user aspect.

**Comment by derimmer** [comment]
@zgrose I am most of the way there but one issue I am struggling with:

At some point I need to retrieve the shaderVisible value from MapShader. There is a setter method but no getter in MapShader.  I can easily add a getter to the ASL shader classes. But I am have trouble with the following:

private <T extends MapShader> boolean getShaderVisibility(ASLMap map, Class<T> shader) {
    Iterator<T> shaderIterator = map.getComponentsOf(shader).iterator();
    if (!shaderIterator.hasNext()) {return false;}
    MapShader shaderObj = shaderIterator.next();
    return shaderObj.getshadingVisible();
  }

This code above shows an error in the return line as getshadingVisible() is not a method of the superclass MapShader.

This is modelled on your code. So shader can be any one of the ASL shader classes. And in the line MapShader shaderObj = shaderIterator.next(), I need to cast shaderIterator.next() to the ASL shader that is in use. For example, if I add (ASLNightMapShader) in front of shaderIterator.next() then the code will run when shader = ASLNightMapShader but breaks when it tests for the other shader classes. How can I add a cast that will always match the class being passed in by shader. I have tried (shader.getClass()) and other variations but can't find one that works.

**Comment by zgrose** [comment]
I think you need to put an Interface on the ASLShaders.

This is the basic idea, but I may have some syntax incorrect. I'll proof-of-concept it out better later today...

public interface VisibilityQueryable {
  public bool getShaderVisibility();
}

public class ASLNightMapShader extends MapShader implements VisibilityQueryable {
...
}

and the shader would implement getShaderVisibility to just return the property.

and then ScenInfo

````
private <T as VisibilityQueryable> boolean getShaderVisibility(ASLMap map, Class<T> shader) {
  Iterator<T> shaderIterator = map.getComponentsOf(shader).iterator();
  if (!shaderIterator.hasNext()) {return false;}
  VisibilityQueryable shaderObj = shaderIterator.next();
  return shaderObj.getshadingVisible();
}
````

**Comment by derimmer** [comment]
This worked. 

However, it led me to the discovery that only ASLNightMapShader uses the boolean shadingVisible value to track whether or not a shader is engaged. Each of the other shaders uses an ENUM (found in the Environment folder) to track the specific level of shader. 

It seems to me that the best course of action is to add the necessary code to each of the newly created getShadingVisible() methods to determine if a shader is on or not. Then to add a line of code to setShaderVisibility() in ScenInfo to set the Shader value by calling a method in each of the non-Night shader classes.  

Does that sound logical to you?

**Comment by derimmer** [comment]
There is less homogeneity across the shaders that one would hope for but I am working away at it. You have given me the right framework to work from and I can see it coming together. 

Night is definitely working. The others are more complex but we can get there.

**Comment by zgrose** [comment]
Ya, the implementations will differ slightly... If you've published your branch to GitHub, I can pull it and take a peek at what you've got an perhaps offer some tweaks...

**Comment by derimmer** [comment]
Will push something when close to working . . . . I keep getting interrupted by RL! Thanks!

**Comment by derimmer** [comment]
@zgrose I have pushed changes to branch dev669 but have not yet PR them into develop. With these code changes there are still two outstanding issues:

1. After applying one of the shaders or changing an existing shader value it is necessary to open the ScenInfo window and click save in order for the setting to be persisted.  I just haven't gotten around to fixing this yet.
2. I have not tested the code in an online situation yet. I am hopeful that it will indeed apply to both players since it is largely managed by Command structures.

**Comment by zgrose** [comment]
Cool. I see one error (do you have the IntelliJ compiler warning set to show?) and one section that isn't hot. I'll toss up a PR to that branch shortly.

**Comment by zgrose** [comment]
@derimmer check out #1800
I think you *almost* had a big bug with the read/write of the properties since the values are read in order (`nextToken()`) so you need to always add new properties to the end of the chain. You might want to consider keeping the true/false and the level right next to each other for similar reasons.

Other than that, the biggest change was to drop redundant fields on ScenInfo and tidy up a couple places with IDEA made suggestions.

**Comment by derimmer** [comment]
> Cool. I see one error (do you have the IntelliJ compiler warning set to show?) and one section that isn't hot. I'll toss up a PR to that branch shortly.

Yes, I get warnings and messages up the ying yang. I can build and run the code I sent you! I must say that IntelliJ has been a bit funky recently . . . . sometimes it reports errors at the class level but doesn't highlight any lines. And other stuff like that. 

Of course, I may just be missing something.

**Comment by derimmer** [comment]
I am having a problem with the re-ordering you have done in setState(). After retrieving the traditional (SAN, ELR, Booby) tokens, the code then looks for more tokens to add to notes. It finds them but what it is actually finding are the shader tokens, It runs through all of them and then gets to the line "nightshd = st.nextToken();" at which point there are no longer any more tokens and the exception message gets called. 

I like your ordering better than mine but I think we need to either (1) find a way to bypass the notes loop if there are no notes or (2) revert the order. 

Could we do (1) by testing the value of the line "String id = st.nextToken();"? If this is "true" or "false" then we have reached the shader tokens. I can't think of any way in which the "id" value would be "true" or "false" if was actually a note token. 

Given that the shader values are always given a default value and added as tokens, it might be preferable to revert the order as we know that those 12 shader tokens will be there and after that we can test for other tokens such as notes which might or might not exist?

I think I prefer option 2. 

Suggestions?

**Comment by derimmer** [comment]
Just thinking. . . . if we open a game saved in a previous version and it has notes, then they will appear in the tokenized string right after the SAN, etc. So we need to read them in that order . . . . 

I will create some saved games in 667 or 668 and add some notes and see what they look like as tokens. Maybe there is some way of distinguishing them.

**Comment by zgrose** [comment]
>>>Just thinking. . . . if we open a game saved in a previous version and it has notes, then they will appear in the tokenized string right after the SAN, etc. So we need to read them in that order . . . .

Right, that was the problem I was trying to avoid, but you've noted the "inverse" issue in that notes look the shader properties...
This is a case study in why people don't encode properties this way. :) Made doubly worse by the open-ended nature of the notes.

Might be better off creating a second class to hold shader properties. Since there shouldn't need to be a UI (I think), might be the easier route... I'll take a stab at that tonight/tomorrow and see if that looks promising or not.

**Comment by zgrose** [comment]
Just following up... been playing around trying to grok the proper way to do what we're doing...
I think we have the right 'actions' but in the wrong places and I want to do this right so that we're not making the problem worse down the road. I seem to have my IDEA fully functional for debugging and iterating, so let me put my noodle on it this coming week. I'm trying to wrap my head around the interplay between a GameComponent, a Command, and a CommandEncoder because it *seems* like toggling a Shader on/off is a Command, which has to be encoded to be transferred over the network (or in the save file) so the GameComponent (i.e. the ScenInfo steps) *seem* like a red herring...
Anywho, just a stream of thoughts at the moment. I also want to double-check that we're not re-inventing tools already present in VASSAL (I have a sneaky idea the infrastructure for all this is already in place).

**Comment by zgrose** [comment]
OK, starting to make sense now....
So the infrastructure for saving/getting shader values is already there, e.g.
`gm.addMutableProperty("lv_level", globalLVLevel);`
But no one is reading them at the right time.

So we don't need to implement our own encoder into ScenInfo, it's already there.

This gives me a new angle to attack the problem... going to create a new branch off 6.6.7 to see if there is just a missing bit in existing code that just needs to be dropped in.

**Comment by zgrose** [comment]
Update... half of what I said above was correct. :)

I have a working prototype for Night that should:

- Avoid all the ScenInfo issues (because I create a new storage container)
- Sends the command for multi-player (I think)
- Sets the shader to the last know value in a given save file (shaders are normally client only and whatever you had last persists across games)
- Has some decent debugging/troubleshooting and error handling code

The *current* drawback is that there is a lot of duplicated code (i.e. a small change in once place has to be done in a lot of places) and the classes aren't very tidy (at least to my standards, which come from the C# world).

I have time and interest in applying what I did to all the other shaders, but I wonder if a quick call/screen-share would be in order to get us both on the same page for what I did and why....

I'm pushing up my branch so you can take a look in branch dev669-before-shader-work

**Comment by derimmer** [comment]
This sounds great to me. I am somewhat limited in my actual coding time over the next two weeks as I have some family visiting. I can certainly do a zoom call though (we have done so before I believe). It would be best to do this week including the weekend rather than next week. I will have a look at your recent push as soon as  I can.

**Comment by zgrose** [comment]
Status update, I took a pass at getting all shader persistence implemented. It's a bit redundant but isn't really a lot of code in each to maintain. Couldn't figure out a good way to create Undo commands for multi-level shaders, but that seems a minor flaw at the moment.

I think I halfway figured out why chat commands throw null into chat when the receiving client doesn't have the correct environment set (in a nutshell, because we're re-parsing the chat text to.... build up the dice stats? that was the part I wasn't 100% on).

The branch dev669-before-shader-work has my files to date. I'll try to get some testing done this week and I might be able to get a little pbem and online test in, as well, this weekend.

I tried to move all the classes that did work into VASL.build.module.shader.* and left the shader classes to just execute the Commands when the button is clicked. I also tweaked VASL.build.model.environment.Environment to be persistence aware and leverage the properties when appropriate.

**Comment by derimmer** [comment]
I have downloaded your code and built the module. I am not getting persistence locally. If I save a game and then shut vasl down and restart, the shader does not persist. Where should I be debugging to see what happens when I re-open the game?
