### ISSUE TITLE
LOS for huts

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#158]
The PTO rules state that all single-story houses having multiple buildings are huts when PTO is in effect. The LOS engine currently has no way to identify these hexes, so these building continue to block LOS.

**Comment by derimmer** [comment]
I will shortly push up a code solution that will be included in 6.6.5. Quite simply as in turned out. The LOS rules logic already existed courtesy of David. Just needed to tweak the terrain types a little bit. 

However, losdata for all boards containing such a terraintype will need to be tweaked. I can do that quite easily but the sheer number of boards make it a larger job so not all los-enabled boards may be fixed by the time 6.6.5 releases and certainly not be the time the next beta is issued (early Sept).

**Comment by derimmer** [comment]
Going to re-open this. The fix to the boards means that los won't work when using 6.6.4 and belo with these boards. So not pushing the updated boards yet.

Plan:
1. Release 6.6.5 this fall with code changes but no board changes. No impact on users. LOS will work on all boards but a Wooden Building to Huts transformation will not (as is the current situation).
2. When 6.6.6 releases (likely Fall 2023) then push the board changes. Most users should be on 6.6.5 by then so even if they don't upgrade to 6.6.6 right away, los will still work with games saved in 6.6.5 when the new boards auto-update.

**Comment by derimmer** [comment]
All VASL changes are in place. Need to change building types in bdXX files with multi-building hexes. Will do this after 667 release and will put out a PSA beforehand.
