### ISSUE TITLE
More robust marsh to water transformation 

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#161]
Flooding a river or stream will convert all connected marsh hexes into river/stream hexes. That's working fine under VASL so far as I'm aware. VASL also properly does not convert marsh hexes that are not directly connected. No problem there.

However, if you need to do a mass convert of marsh hexes into water (scenario BC15 has prompted this request) there's no way to do it except by using "Ocean" draggable overlays, which is a pain if you have a lot of marsh hexes in your playing area.

Marsh is already an option in the "Transformations" menu; if "pond" or "water obstacle" or however you want to describe it were to be added to that menu, then you would have the "marsh -> pond" option which would do the trick nicely. (Presumably the easiest way to do that would be to do a colour change on the "xxx -> level -1" transformation that already exists?)

I guess that would require an update on every board that features marsh hexes; maybe it could be done at the same time that the buggy PTO "swamp pattern" transformation is fixed?

**Comment by derimmer** [comment]
I have spent a good bit of time on this one and the range of Marsh transformations available in the Transformations menu. I have added a "Marsh to Water" transformation that seems to be working and have fixed some, if not all, of the other Marsh transformations. I am going to mark this issue closed and if any specific problems appear I will create new issues. 

The principle cause of the problem seems to be that Marsh colours used on actual board gifs do not match the colours expected in the ColorSSRs in the SharedBoardMetaData.xml file. For "Marsh to XXX" transformations that involved any and all Marsh on a board, regardless of level, it was easy to fix this by adding all possible Marsh colours to the ColorSSR color map. However for specific transformations such as Marsh0 to Level-1, the same approach cannot be used as it will changes every Marsh pixel on a map and not just ones at the specified Level. I have tried to ensure that all Marsh colours at a given level are included in the transformation from Marsh at that level to another terrain type. 

There was an equal need to rework some of the LOSSSRules in the SharedBoardMetaData.xml file to changes the type from terrainMap to terrainToElevationMap. I amended several existing ones and added a few new ones. I may have missed some from/to combos and they can be added if we get any bug reports.
