### ISSUE TITLE
Orchards Out of Season with PTO

### ISSUE THREAD

**Issue by Wargamerx** [vasl-developers/vasl#177]
If you select the Orchards Out of Season checkbox with a PTO Terrain selected, the orchards disappear completely (unless the orchard is on a -1 level hex, then it shows up with a level 0 color scheme - see board 24).

**Comment by bkemp01** [comment]
I don't believe this is a bug as the PTO Terrain dropdowns are designed for applying **all** PTO transforms which include Palm Trees. Since Palm Trees can't be "out of season" the Palm Trees overlays don't have the color info to turn "out of season". Instead the Palm Trees disappear on Level0 terrain and on non-Level0 they appear in the Level0 color (due to the Palm Trees color being the same as Level0 Orchards.

The correct way to handle PTO with Orchards out of season is to not select PTO Terrain from the dropdown list but instead select the individual PTO transforms required (i.e. NoRoads, Bamboo, DenseJungle, etc.) but make sure PalmTrees is not selected and check the Orchards out of season box.

On board 76 when using Orchards out of season and the PTO Terrain dropdown you get these settings...
![image](https://user-images.githubusercontent.com/4276070/36074916-cb131496-0f14-11e8-8bf8-2200101d10c4.png)
Note Palm Trees is selected.

and it looks like this...
![image](https://user-images.githubusercontent.com/4276070/36074934-ffe121d6-0f14-11e8-9402-62fa50f01bf8.png)
Notice the Palm Tree "holes" in the Level1 hill of BB6.

Using these settings instead...
![image](https://user-images.githubusercontent.com/4276070/36074897-904928b4-0f14-11e8-8a00-668e0e6e2472.png)

you get the correct effect...
![image](https://user-images.githubusercontent.com/4276070/36074870-5087ab4c-0f14-11e8-8b9a-4ccdbdbc0f2a.png)

**Comment by derimmer** [comment]
Closing as Brian's response deals with the issue.
