### ISSUE TITLE
custom turn and phase counters resetting side images

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1810]

**Comment by derimmer** [comment]
@zgrose can I pick up on your learning from setting all the Shader Global Properties? 

For the Custom Phase Wheel, you can set a Nationality image for each side. This is automatically resetting to blank when you open a saved game. 

The selections are stored to Global Properties.  Identical Global Properties are found in two places in the buildFile (and in VASSAL.Editor mode) at lines 4-8 (just before your Shader properties) and 8831-8834. If I delete either one of the two sets, I start to get BadData messages in Chat when I try to add the images and the counter doesn't work properly. 

Selecting an image is handled by a prototype, CustomSide, which is added to the Phase Wheel counter traits in VASSAL.Editor.

Any thoughts about how to handle the Global Properties? I am pretty sure we only need one set? Should I delete both sets and then recreate one of them? If so, should I add the Global Properties under the Map node in VASSAL.Editor (this can be done)?

Does anything else occur to you? 

TIA!

**Comment by zgrose** [comment]
I must've accidentally duplicated the Turn global properties when I was moving things up and down (order in the build file matters)?

>>If I delete either one of the two sets

Are you deleting them in the build file manually or via the Editor? You might want to try zapping the ones in the middle and leaving the ones at the top in the xml file itself since the Editor might be getting confused because the names are the same?

>>If so, should I add the Global Properties under the Map node in VASSAL.Editor (this can be done)?

Looking at the dialog, I'm not sure it matters.

<img width="454" alt="Screenshot 2024-09-22 135227" src="https://github.com/user-attachments/assets/8e2ed096-ce3d-4d26-9a70-8675a44a2096">

Do you have a branch published that I can hook into? I would think just zapping the block of properties at 8831-8834 is the correct solution.

**Comment by derimmer** [comment]
And you would be right! I just tried it and it fixed the problem. 

I had thought about that but figured if I deleted the properties in VASSAL.Editor, it would have the same effect. But obviously not.

Thanks for the help!
