### ISSUE TITLE
Add HIP option to all counters

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#200]
HIP on some counters doesn't make sense, but for simplicity we could add it to all counters.

**Comment by Taschenschieber** [comment]
As it currently is, this messes up the order of commands for some counters, e.g. the phase wheel. That is really annoying so I would recommend either fixing it before the release or pushing this back to 6.4.

**Comment by davidsullivan317** [comment]
Do you know if adding HIP changes the location of the HIP option on existing counters? That would be a pain. But if we're adding it to new counters it don't know that there's a "right" place to put it.

**Comment by Taschenschieber** [comment]
Adding it above all the existing options seems like the worst choice to me, though, because that's where they get in the way the most. I'd suggest putting the option at the bottom - seeing how it was previously impossible to HIP the affected counters, it's not really the most important option there and it would be better UI design to put it to the bottom of the menu.

On the existing counters, I haven't noticed any changes.
