### ISSUE TITLE
Japanese crews from 6.2.1 setups disappear

### ISSUE THREAD

**Issue by zgrose** [vasl-developers/vasl#211]
vasl-6.3.0-Snapshot-20150327

```- Bad Data in Module: Unrecognized image type ja228C```

![screen shot 2015-03-29 at 9 45 08 am](https://cloud.githubusercontent.com/assets/5044847/6886624/505c1552-d5f8-11e4-8c6a-dd92107ac005.png)

**Comment by davidsullivan317** [comment]
Hi Zoltan - can you still recreate this issue in the development build and, if so, can you send me the saved game so I can recreate it?

**Comment by zgrose** [comment]
You won't need a saved game. The graphics files are bad. I'll grab some corrected images for you.

<img width="1024" alt="screen shot 2015-09-12 at 9 17 31 am" src="https://cloud.githubusercontent.com/assets/5044847/9832423/3be6b4fa-592f-11e5-9301-085d881480af.png">

**Comment by zgrose** [comment]
Ok, the good images are in the repo https://github.com/vasl-developers/vasl/blob/develop/dist/images/ja/ja237H.gif and https://github.com/vasl-developers/vasl/blob/develop/dist/images/ja/ja228C.gif

**Comment by davidsullivan317** [comment]
In your screen shot I'm looking at Oracle SQL*Net connect strings from my work machine, which is totally weird. I check the images in the 6.2.1 and 6.2.2 vmods on vasl.info and they are correct. These corrupted images were never checked in and are not in the official builds. I'm assuming I corrupted one of the development/test builds via a cut/paste error and sent it out to you guys, since you and Daniel are the only ones that have reported it. Sorry about that. Anyway, totally bone-headed move on my part.
