### ISSUE TITLE
RB V2 map missing sewers

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#226]
There are three hexes that should be marked with sewer enterence locations that aren't
A10 (Road Skulpturnaya Street)
D39 (Hex south of the culvert location)
S38 (Gully with cliffs on both sides)

**Comment by BigAl737** [comment]
I’ll make the corrections David. Thx.
Allan

From: David Sullivan 
Sent: Wednesday, June 10, 2015 6:53 AM
To: vasl-developers/vasl 
Subject: [vasl] RB V2 map missing sewers (#226)

There are three hexes that should be marked with sewer enterence locations that aren't
A10 (Road Skulpturnaya Street)
D39 (Hex south of the culvert location)
S38 (Gully with cliffs on both sides)

**Comment by BigAl737** [comment]
Fixed (#226). In addition I added gutted factories, ground snow, and a non-rubbled Chemist shop. I'm using this as a test of my Git Hub competency. I'll commit my local source folder by adding a new folder for RBv2 to boards. My apologies if I screw anything up but since I'm only adding to the source I think I'm okay. Sam, the folder contains the updated bdRBv2. Please post this for download with the other VASL historical maps. If this works I'll start on other map issues and get them uploaded the way you real programmers do.

**Comment by davidsullivan317** [comment]
Allan - I'm happy to tell you that you've earned the VASL GitHub Power of Persistence Award. Well done!

**Comment by BigAl737** [comment]
Alright!

I’ll tackle some more stuff now.
