### ISSUE TITLE
ASLBoardPicker.updateBoard() only checks for difference in version

### ISSUE THREAD

**Issue by zgrose** [vasl-developers/vasl#299]
If one has an updated board locally, the updateBoard() function seems to treat that as a reason to replace the newer board with an older one from the repo.

```
if (boardDir != null && availableVersion != null && !b.getVersion().equals(availableVersion)) {
```

We should probably convert to a number and only download if the available version is > the board version.

**Comment by derimmer** [comment]
Since I have been playing around with changing boards locally as I try to add los checking to HASL boards, I have come across this issue a number of times. 

You are correct about current functionality. I can't remember the number of times I have cursed as the update function overwrote a board I had changed locally!😀

But that is all my bad. If someone has figured out how to change a board locally then they should be able to rename it or otherwise avoid the update function. 

Personally I would be inclined to leave board update as it is. I think this will help avoid the proliferation of untested or non-conforming board versions.

**Comment by davidsullivan317** [comment]
It's a PITA but the trick is to leave the version number alone until everything is done and dusted and then update the version number in the final check-in.

Conversion the version number to a number would be fine but we'd just have to ensure we understand exceptions.

**Comment by bkemp01** [comment]
Agree with Doug, if truly a custom local board then it really should be
renamed. And with David for testing updates that are yet to be published to
the repo, keep version same until testing is complete.

**Comment by zgrose** [comment]
Such effort to defend what is essentially a 2 minute bug fix. =P

**Comment by bkemp01** [comment]
Sorry, not much of a coder so I wouldn't know. Just seems prudent to me if one is making local custom changes to boards that they should also give them a custom name.

**Comment by zgrose** [comment]
I put a prototype smarter check in the branch update-when-newer-only.
