### ISSUE TITLE
Finnish 87* ART K/95 counter off when malfed

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#317]
Bug: Finnish 87\* ART K/95 counter: When this Gun malfs, the counter ends up pointing at a hex side instead of a hex spine. Actually, it ends up pointed 90-degrees off of where it should. I haven't tested the other Finnish Guns yet.

**Comment by BigAl737** [comment]
A bunch if not almost all Finnish guns have this issue. Fixing this is a bunch of work to modify the broken side gif image to show an unchanged facing. On a positive note, when the gun is repaired it goes back to its original facing. This shows the sequence...functioning...malfunctioned...repaired:
![image](https://cloud.githubusercontent.com/assets/10384413/24524814/6d953ef4-1544-11e7-82e6-0e5f650030f4.png)

Maybe a help file note to users would suffice since once repaired, this isn't an issue anymore.

**Comment by bkemp01** [comment]
This is a side effect of using scanned counter images for the VASL counters.

**Comment by bkemp01** [comment]
Since this affects a number of counters from Hakkaa Paalle I'll make a list and start a new issue to cover all of them.

**Comment by apbills** [comment]
19 total Finnish Gun counters have been changed to have their malfunctioned side CA match the non-malfed side orientation.  I am sending Doug a zip file with the images to incorporate into 6.6.8-beta7.

**Comment by derimmer** [comment]
Much appreciated @apbills. I will get them into the next beta which should come out this week.

**Comment by derimmer** [comment]
Added to 668beta
