### ISSUE TITLE
VASLize board 76

### ISSUE THREAD

**Issue by styson** [vasl-developers/vasl#337]
new board in WO '17

**Comment by bkemp01** [comment]
Looks like this fell through the cracks, I'll take it.

**Comment by bkemp01** [comment]
bd76 had been uploaded to vasl/boards/src. Will someone please add the LOSData.

Thanks

**Comment by derimmer** [comment]
I should be able to do so in the next couple of days.

**Comment by derimmer** [comment]
Brian

 

I can’t find bd76 files in vasl/boards/src?

 

Doug

**Comment by bkemp01** [comment]
I just synced again, take a look when you get a chance please.

________________________________

**Comment by derimmer** [comment]
Got it!

**Comment by derimmer** [comment]
Hi Brian

 

I tried to add the LOSData today. No go. The problem seems to be that the SSRControls file is missing. Looking at other board files this seems to be an html file. Not sure what it does but it appears to be needed!

 

If you can add the file today, I can build it today, otherwise I wont be able to get to it until next week. Next 4-5 days are totally booked. 

 

Doug

**Comment by bkemp01** [comment]
Not sure Doug, my understanding is that file is only needed if there is to be an SSR or BSO overlay. I wouldn't know what to put in the file since this board has no SSR or BSO overlays. There are several boards that don't have those type of overlays or that file, i.e. bd75 & bd74.

________________________________

**Comment by derimmer** [comment]
OK. Will investigate further but can’t do until next week. 

 

Doug

**Comment by derimmer** [comment]
I have identified the problem (you were right Brian, nothing to do with SSRControls). Now I have to find the solution! Working on it!

**Comment by bkemp01** [comment]
It seems everything is ready now? I just need to add it to vasl-website?

**Comment by derimmer** [comment]
I have pushed the zipped bd file up to VASL-Website on GitHub along with the updated versions file. It just needs to be made visible on the website. I forgot to do that.  Go ahead and do so if you know how (or ask Sam if you don’t).

**Comment by styson** [comment]
I updated the link for board 76 so it should soon be visible.

**Comment by bkemp01** [comment]
Thanks Sam and Doug

________________________________

**Comment by bkemp01** [comment]
Hi Doug, there seems to be a LOS problem on this board involving orchard hexes not reporting as a hindrance unless the thread touches a green orchard symbol. Would you please take a look when you get a chance. The background is in this GS thread...
[http://www.gamesquad.com/forums/index.php?threads/board-76-now-available-at-vasl-info.135015/](http://www.gamesquad.com/forums/index.php?threads/board-76-now-available-at-vasl-info.135015/)
Thanks

**Comment by derimmer** [comment]
I am out of town for about a week. This did not happen on my machine but I am not surprised. I think I know what is causing this. Will fix when back.

**Comment by derimmer** [comment]
Brian

 

I believe I have this fixed now. Updated files pushed up to GitHub: vasl, vasl-boards-extensions, vasl-website. 

 

It sometimes take a few minutes to become available on the website. 

 

Version number bumped so it should update via auto-sync. 

 

Please give it a test but it seemed to work fine today.

 

Doug
