### ISSUE TITLE
Reminder to begin recording log

### ISSUE THREAD

**Issue by mistertakai** [vasl-developers/vasl#34]
Can we get a reminder or warning when we begin typing with no log being recorded (when replaying a log)?

**Comment by mistertakai** [comment]
@LanceLGit / @uckelman : are you tracking this somewhere else or is it already fixed? Would like to close older tickets here. Thanks!

**Comment by uckelman** [comment]
It's possibly in VASSAL's bug tracker. If you're waiting for me to fix this in 3.2, though, you're going to be waiting forever. When I next have time to work on VASSAL (after we've moved house), I'm going to be putting all my efforts into V4. If someone submits a patch, I'll review it.

**Comment by mistertakai** [comment]
Ok, thanks for the heads up. I'll have a look at the VASSAL 4 discussion, I remember we discussed it in Heidelberg. Meanwhile, I'll close this minor change request.

**Comment by uckelman** [comment]
Wait, I see above that Lance has already made a patch. I will have a look at that.

**Comment by mistertakai** [comment]
Thanks, Joel - I left you a difficult comment on the VASSAL 4 thread in return.

**Comment by uckelman** [comment]
I've looked at Lance's patch now. It repeats quite a bit of code. I think this is the right idea, but there might be a better way of implementing it.

**Comment by uckelman** [comment]
Let's aim to get this sorted for 3.2.17.

**Comment by LanceLGit** [comment]
It has been a while.  Let me take a look at this again over the next few days.

 

    On Friday, April 1, 2016 6:01 PM, Joel Uckelman <notifications@github.com> wrote:
 

 Let's aim to get this sorted for 3.2.17.—

**Comment by uckelman** [comment]
Having a look now...

**Comment by uckelman** [comment]
Lance, what's the behavior you're intending this to have?

**Comment by LanceLGit** [comment]
Joel,
I think the issue is for a user to be notified whenever he has done something that should be logged, e.g. rolling a die, moving a piece, entering text, etc if logging has not been started.  What I have done is to display such a notification once only.  It will not be displayed any more whether or not the user has started the logging.  

If the user selects "Yes" to start logging, then the file will start logging from the last action he does that initiates the logging notification.  If he selects "No", then no logging will start and whatever he does from that point on will not cause the notification dialogbox to pop up any more.
I used the Pacific War game to test my code.  

Will there be anything that I might have missed or any other game that I should test it with?  

Lance





    On Thursday, May 26, 2016 5:41 PM, Joel Uckelman <notifications@github.com> wrote:
 

 Lance, what's the behavior you're intending this to have?—

**Comment by davidsullivan317** [comment]
Did this make it into VASSAL 3.2.17?

**Comment by uckelman** [comment]
IIRC, I did a build for testing but didn't get much in the way of comments on it. I can revisit this in the coming week.

**Comment by davidsullivan317** [comment]
Joel - do you have a reference to the VASSAL change for this? I'm going to close our issue.

**Comment by uckelman** [comment]
Turns out we've done this as Bug 13153 for 3.3.3. Check the beta we'll be releasing soon.
