### ISSUE TITLE
interesting idea for assisted-mode VASL

### ISSUE THREAD

**Issue by styson** [vasl-developers/vasl#395]
Hi! I'm 25 yo and new player of ASL. I can play at ASL only by VASL because i don't know real opponent.
I think that if VASL would be more easy, there would be many more players. I was thinking to make an "easy game mode" for new player. For examples: I select attacker units and target unit and VASL calculate LOS, FP, DRM, Hindrance ecc... and after give me IFT result without need to check the tables... or when i move units, VASL could show the remaining MP or legal movements. I know that old players don't like much it, but i don't talk about delete traditional system. Only add this "simplified" mode and make VASL more automatic and easy, without changing its nature. This way could help new players to learn ASL system and make more big our community. I don't know if this is possible... but i could help you in this work. 

Regards,
Stefano Oddo
stefanoddo@hotmail.it

**Comment by derimmer** [comment]
Well, since you mention it. . . 

 

(Long post to follow, includes 3 images without which the text is pretty much nonsense. Not sure if GitHub will process them. So if the images don’t show and you are actually interested in this, email me at dougrimmer@rogers.com <mailto:dougrimmer@rogers.com>  and I will forward you a viewable message).

 

I have spent about 15 years or so puttering away at very much what he is asking for. I was trying to do it using Microsoft tools, in particular VB. That simply became unworkable as VB fell further behind. So, I have switched to java and hope to use the existing VASL code base as a starting point. Since I am completely self-taught, the challenge is daunting but hell, I need something to do in retirement! It is actually a joint project with a buddy of mine. 

 

Basically, I agree with the comment that this would actually be a computer game and not ASL online. Two different things. Both good. 

 

Here are several examples of what we were trying to work on. The people who hate LOS checking will hate this too. 

 



 

What you see here is the VofG map. The 238 has just moved from O7 to O8 as the green dots indicate, the 2 over the 238 indicates that this particular move cost 2 MP. The 2-2 below the 238 indicates that the unit has 2 MP left and has spent 2. The blue items above the Russian units indicate the possible defensive first fire from each hex with a Russian capable of firing. The 4-1 in Q9 indicates that there is a good order unit in the hex in addition to the broken one (our approach to stacking was just to show the top unit with mouse over showing the full contents a la VASL; right clicking a counter moves the next counter in a stack to the top). 4FP with a -1 DRM (-1 NAM, -1 City Square, +1 Shellholes). The 2-1 over R8 indicates that it can fire a 2 down 1 shot at the target. At least one unit is at long range as signified by the orange shading. If they were adjacent to the moving unit, say in P8, the shading would be blue. The white shading in R5 indicates the presence of a unit capable of fire but without LOS to this particular moving unit. 

 

Of course, no FP or modifiers would be displayed for ? units. 

 

Very much a work in progress but we are getting there. If you were to select the units in R9 all of this would go away and you would be able to generate an actual attack. You could also select R9 and Q9 and then generate the attack.  

 

This image shows a combat resolution screen. The 338 in G7 has just fired on a broken 226Q which was in G6 (and is now dead). Prior to the Fire button on the panel being clicked it is possible to add or subtract both units and drm. If there were multiple target units selected then they would show up as tabs given that FP and drm can differ depending on circumstances. Clicking on the Fire button activates the result calculation and implementation. In this case, a broken 226 died and was removed. All ELR, Sniper, HoB results are determined and implemented. Results are show in the text boxes at the bottom of the panel. Things like MG ROF and cowering would show in the Firer text box.

 

LOL. Note that a 3 DR on the 6 FP is not an NMC. So this was not bug free! We did have this working but as we added new wrinkles we obviously broke something!

 

Notice that the units (and SW) have unique identifiers as per ASL itself. Info on each unit was captured in a data file and maintained from playing to playing. 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

The final snip shows the result of selecting Show LOS on a dropdown for the 238 in A10. It shows what hexes he can and cannot see. Blue is same hex/adjacent. Clear is normal range. Orangey brown is long range and yellow is LOS but no range. White is out of LOS. Pretty poor on the graphic display but I think the idea is interesting. If I recall the red “1” in the image had to do with whether various levels in a hex aside from the ground level could be seen. Which highlights the dual challenge that we were working on: (1) creating the functionality to determine things like LOS, combat options, and movement options and (2) displaying them in a user-friendly way (so far epic fail on the second part!!). 

 



 

That is just a start of what we trying to do. Happy to share more and discuss further. Our goal, as I said is to try and pull a lot of our functionality into a version of VASL. Not sure if it will work or if it would actually be useable (might be pushing the copyright envelope too far for MMP’s tastes in addition to user reaction).  I am happy just to work away, solving various problems and learning. Beats the hell out of Suduko. 

 

Doug

**Comment by zgrose** [comment]
You can't email pictures into Github, but you can drag/drop them into the issue.

**Comment by Stevenovich** [comment]
Hi! I'm boy of the email. I was thinking to make assisted-mode VASL only for Starter Kit for example. Just to help new players to learn basic rules. Is possible ?

**Comment by BigAl737** [comment]
Stefano, Welcome to the ASL world. Glad you're with us. There is a guy developing a computer program that does exactly what you're wishing for. Last I recall he's gotten pretty close to a product that's ready for testing. Unfortunately I can't recall where I saw this or give you a link and for that I do apologize. I'm almost certain he's posted on Game Squad a few times with pictures of his program. I'll see if I can find it for you but I'll bet you can do a better search job than I.

Doug, what you're working on looks pretty cool! I've been playing around with improved graphics for
VASL-TNG...vasl for the next generation :-)

**Comment by Stevenovich** [comment]
@BigAl737 Thanks for you answer! I tried to find something... but i can't. Do you remember anything more about this post?

**Comment by BigAl737** [comment]
I'll do some poking around. It's in the grey matter within my brain. Unfortunately there's too much grey matter atop my brain :-)

**Comment by Stevenovich** [comment]
Maybe I've found something.. http://www.gamesquad.com/forums/index.php?threads/asl-computer-assist-program.20980/ 
They talk about SALSA, ASLGAP, ASLAP, but i didn't understand if these programs are what i search

**Comment by BigAl737** [comment]
That's not what I recall Stefano. I posted a GS thread asking for help:
http://www.gamesquad.com/forums/index.php?threads/computer-asl-program.130153/

The reply from Witchbottles mentioning Lars isn't what I recall either. I'll still keep searching.

**Comment by BigAl737** [comment]
Stefano, found it. Well the guys on GS found it.

Check out this post and the post that follows:

http://www.gamesquad.com/forums/index.php?threads/computer-asl-program.130153/#post-1865709

**Comment by Stevenovich** [comment]
Thanks!
