### ISSUE TITLE
Using up/down arrows is causing ghost LOS actions

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#417]
See this thread: 

http://www.gamesquad.com/forums/index.php?threads/strange-vasl-6-4-0-error.131012/

**Comment by derimmer** [comment]
I have been trying to fix this. I was finally able to replicate it and I think I know what is happening. 

 

In your post on GS, you wrote: “There was a gap in the LOS logic where using the up/down arrows to change the level was only showing on the local machine. It seems that fix is not checking if the LOS is currently active.”

 

If I am understanding things correctly, because VASLThread implements KeyListener, any time a key is pressed during a game VASLThread.KeyPressed(KeyEvent e) is going to be invoked. This method contains code that processes the Up/Down Arrow key press when changing levels. And this code is being triggered whenever an Up/Down Arrow key is pressed. 

 

The KeyEvent() method contains a test:

 

if (!isEnabled() && legacyMode) {
    return;
}

 

but this is insufficient to stop the method from being processed, regardless of the context of the keypress, because legacyMode is always false if the LOS engine is enabled. 

 

So, I need to add a test in to KeyEvent() that will only process the rest of the code if an actual LOS Check is in progress – or active as you said in your GS post. Not surprisingly, you understood what was happening here right at the start. It took me a little longer to get there!!

 

Now I will try to figure out how to add the test. 

 

Doug
