### ISSUE TITLE
How hard is it to make a VASL preference?

### ISSUE THREAD

**Issue by zgrose** [vasl-developers/vasl#428]
Since we know counter drawing issue is essentially a toggle of run-this-code-or-not how easy is it to add a preference into VASL with a checkbox to "Display full-color counters in stacks" or something like that? Might be a good middle-ground to satisfy both sides in the Right Of Inspection camp.

I have no experience with adding preferences to looking for an assist.

**Comment by zgrose** [comment]
BTW, I was thinking it might be quickest/easiest to just shove the counter graphics up a couple pixels when there is an exposed element. Shifts the burden from code to pixel pushing.

**Comment by davidsullivan317** [comment]
It's easy to add preferences, although we should be careful to limit the
number so folks are not overwhelmed.

See the LOS code for a clear example.

**Comment by BigAl737** [comment]
I experimented with this a while back and as I recall the pixels you’re trying to hide become visible again as you zoom out. Since the pixel space on the counters is limited, you can’t push the pixels up very far. It wasn’t a matter of just pushing the data up by a couple of pixels. Zoom out far enough and you can see the data again unless you pushed the data up so far as to be impractical.

Allan

**Comment by zgrose** [comment]
Good to know!

**Comment by BigAl737** [comment]
I was messing around with VASL-TNG (VASL for The Next Generation) and was wondering if any thought has been given to making the graphics a little bigger for VASL 4.0. In the screen shot below, 1/2" counters are 75x75 pixels and 5/8" counters are 94x94. The map has been blown up proportionally.

![vasl-tng](https://user-images.githubusercontent.com/10384413/28857698-c57f019e-76f7-11e7-81f7-b1be2d7469ad.jpg)

Besides better detail, you can do cool things like make turrets rotatable. While the screen shot is at 100% zoom, I use the 50% zoom level as a default. This helps the map fit better on my screen while leaving enough resolution to decipher the pieces. Since the mouse over function always displays the counter at 100%, it's easy to grope more detail when you need by simply placing your mouse over the counter. Works great for reading the fine print on the back of vehicle counters.

I've imported all counters to VASL as PNGs. I have found that the current version of VASSAL is not quite ready for SVG. Besides the known quality issue with rotating SVGs within VASSAL, I've had bad luck with getting SVGs to import decently into VASL. Truth be told, they look terrible. The PNG images display much nicer.

And yes, even at this scale, when you stack counters and zoom out, you still can see some data bleed on the counters below.

It's all a pipe dream I know :-) but I throw this out there as food for thought.

Al

**Comment by davidsullivan317** [comment]
Boy, that is a pipe dream worth having. It would be a lot of work, I'm
sure.

If we change the size of the maps I'm sure they would all have to be
reworked.

Anyway, love where you're going with this.

**Comment by zgrose** [comment]
Technically, the size of the maps and the size of the counters are the user's preference. If I zoom to 300% to shrink to 25%, the numbers of pixels used by the counter will triple or quarter. It's the resolution of the files that makes the counters look poor when zoomed.

Anywho, it seems like dropping in a toggle for render path 1 or 2 is the only practical bandaid to make everyone happy(er).
