### ISSUE TITLE
Update FB bd files to 6.0+ 

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#470]
The FB bd files do not respond to most of the current bd standards and need to be updated.

**Comment by derimmer** [comment]
I am starting work on this. I need to add the colors, colorsSSR, overlaySSR and SSRcontrols files to the bdXX for each FB board. Are these files standard or do they need customization for each new bd? Can I simply copy them over from a recent board such as 80?

**Comment by bkemp01** [comment]
I'm not sure I understand what it is that we are looking to fix here. Is this referring to the fact that this HASL board doesn't respond to terrain SSR changes?

Many HASL boards exhibit this behavior because they are not "painted" with standard geo board style colors and patterns. This means in order to support terrain SSR changes the board would need to be re-drawn using a defined color palette and patterns that could then be accommodated by the files you have mentioned.

This would be a significant amount of work requiring high quality source images or scans. I do not see where we currently have any source files in the repo for this board.

**Comment by bkemp01** [comment]
To illustrate, note the differences in the below images. The HASL board is not crisp and colors are not uniform compared to the geo board because the HASL baord was created by simply scaling a high quality source image down to VASL resolution. The geo board is actually hand drawn which is also why it takes so much time to do them.

HASL
![image](https://user-images.githubusercontent.com/4276070/61882326-466fcb00-aec6-11e9-946a-dbd288d9e377.png)

Geo
![image](https://user-images.githubusercontent.com/4276070/61882339-538cba00-aec6-11e9-8a68-e0fa484c1d7e.png)

**Comment by derimmer** [comment]
I am simply trying to update it to version 6.0 standards. Which means adding a Boardmetadata.xml file and the files mentionned above. I am not sure that doing so would change anything for users. I was then going to add the source files to the repo. 

Using files copied from bd80 and an updated Boardmetadata.xml file, I have been able to create a bdFB file that continues to work as the current one does. I am certainly not intending to update the graphic image. That is way beyond my capability.

**Comment by bkemp01** [comment]
OK (whew!) sorry for the confusion. For this and most HASL boards the only file required should just be the Boardmetadata.xml.

Here is what the other files are used for...
colors - defines the color palette used to enable colorSSR terrain changes.
colorSSR - defines the rules which substitute one color for another when certain SSR terrain settings are applied (i.e. snow, mud)
(the above 2 files are really only needed if the colors or rules need to be customized for a particular board since a certain version of them is included in the VASL build, but frequently they are included anyway just to be safe)
overlaySSR - defines any overlay image files and placement coordinates, called upon by certain SSR terrain changes (i.e. DenseJungle, LightWoods)
data - seems to be legacy but (in my testing) still needed if using overlaySSR which is pretty much every geo board.

The boardmetadata.xml looks to account for all of the above conditions but I have not had complete success in getting everything to work using just this file :(

**Comment by derimmer** [comment]
Thanks Brian. I may be doing work for no real gain. But consistency is a virtue, at least to my pedantic mind!

**Comment by davidsullivan317** [comment]
As Brian mentioned the only file required is the Boardmetadata.xml. Simply leave out all of the elements for colors, SSR changes, etc. and test thoroughly.
