### ISSUE TITLE
Simplify board updates

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#482]
Our current method of updating and distributing boards leaves a bit to be desired. The source of most boards is in the code repository but users actually download the boards from vasl.info and/or the vasl-boards-extensions repository. 

I'd recommend the following:

It's time to delete the vasl-boards-extensions repository. Let's move the compiled boards into the vasl repository. This would require a vasl code update, and we'd have to keep vasl-board-extensions current for while, but I think that's worth the effort.

We can also explore having vasl.info point directly at the board files in the vasl repository and not move them to the web service. We'd probably lose the ability to offer groups of boards for download, but perhaps the board compiler could be extended to do this as well. 

The extensions haven't been touched in 4-5 years and they're kind of a mess. But we should probably sift through them as keep the ones that are still used. Since we don't really maintain these they could live solely on vasl.info.

**Comment by derimmer** [comment]
Just did a quick check: BoardVersionChecker.java in the VASL module uses a variable "boardRepositoryURL" to find the board directory for autosyncing. The value of this variable is stored in the buildFile in VASL and is currently set to the vasl-boards-extensions repository. Should be simple to redirect it to a folder in the vasl repository. 

While this, and related changes, would allow us to do away with vasl-boards-extensions over time, it would not change the current requirement to create and push to gitbhub, 3 distinct sets of "board files":

1. the source files for the boards, currently stored in vasl
2. the compiled version of the board, bdxx, currently stored in vasl-boards-extensions
3. the zipped version of the compiled board, currently stored in vasl-website

Heavenly peace and harmony would be obtained if we could move to a situation where updates of the source files in vasl would automatically trigger creation of the compiled board and the zipped version. 

Since map eleves probably need to create the compiled board file in order to test it in any event, perhaps we can have them push both new source files and a new compiled board to github and then automatically create the zipped file in vasl-website. Possible?

**Comment by davidsullivan317** [comment]
Do we really need zipped versions of the boards? The board archive is already zipped. I’m assuming this is only for the website? Can we just point the website at the compiled board for download? Probably a question for Sam.
 
Also, remember we only maintain the source for a subset of boards we distribute. Any improvements will have to account for that.

**Comment by derimmer** [comment]
Only one of bd1-79 (including 1a-9b) in my boards directory is over 1MB in size. So, clearly, no we don't need no stinkin' zip file versions of the boards to enable quick downloads. Maybe there are other reasons.

**Comment by zgrose** [comment]
There are 2 problems with the bdXX files that placing them in a zip mitigates.
1- Extension-less files sometimes are given extensions by eager browsers.
2- Eager browsers/OSes can helpfully unzip files on download.
But there is certainly no compression reason as the bdXX files are already compressed zips/jars.

What would be super-sweet since VASL will grab a board for you if the save file references it, would be if the board picker listed all KBU (Known Board Units) along with whatever might happen to be in your boards folder (personal boards, 4th party boards, etc) and so you never *have* to download anything from the standard set.

Less sweet but less code, just stuff all the KBU in a single download and let people grab them manually once and then the auto-updater grabs the updates as needed. Sure it's a big file but we have moved past the days of 14400 baud modems so maybe an option.

**Comment by davidsullivan317** [comment]
"What would be super-sweet since VASL will grab a board for you if the
save file references it, would be if the board picker listed all KBU (Known
Board Units) along with whatever might happen to be in your boards folder
(personal boards, 4th party boards, etc) and so you never *have* to
download anything from the standard set. "

This is a great idea. We could just read the versions file - maybe even add
a description of each board in the pulldown.

**Comment by derimmer** [comment]
Genius, Zoltan, just genius. I love the idea of automatically listing all the core boards as part of VASL. Anytime the users clicks, bamn, autosyncing serves up the most recent version. 

Plus, you must be the first person in 20 years to usefully include the word "baud" in a sentence. Who even remembers what a baud is/was?
