### ISSUE TITLE
Board selection list should include boards available for download

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#485]
When a user goes to select boards, the list could include boards available for download as well as boards already downloaded. These might be marked with notation:

23
24--update to v3
25--download
26
27

etc.

This might also include a preference, so that those who don't want to see longer lists could ignore boards that need downloading, and it also might allow them to list boards by status, so boards already downloaded would be first, then boards available for downloading are listed after.

**Comment by derimmer** [comment]
Personally, I don't think we need the notations. The whole point would be to present the full list of MMP boards and let autosyncing take over from there. Doesn't matter to the user if their home directory is up to date. Click on a board; get a board. Always the most recent version. You don't need to know more than that. IMHO.

As for a preference, I would suggest that we start by including by default only the MMP boards (and even there I would exclude HASL boards). For all other boards, I would use the current system: display only those that are on the user's local device and have autosyncing update them as required. This leaves the user free to manage which boards they see beyond the "core" set. Want to see additional boards, download them. Don't want to see them, don't download. 

This is just my thinking. We are on to a really, really good idea here and should take some time to think this out.

**Comment by derimmer** [comment]
Yes indeed.

**Comment by styson** [comment]
JSON would be best, right?

**Comment by styson** [comment]
Good point, @davidsullivan317. 
JSON is easier to construct and read, but in this realm XML is likely better since VASL knows how to use it.

**Comment by derimmer** [comment]
How is JSON used by the website and would it possible to replace it with an XML file?

**Comment by styson** [comment]
The boards.htm page pulls the versions.json, then loops through each of the boards and plugs the board version into the dom element for each board.
```
  $.getJSON( "./boards/versions.json", function( boards ) {
    var items = [];
    $.each(boards, function(id, version ) {
      console.log(id + " " + version);
      $("sub.version."+id).text("v"+version);
    });
  });
```

**Comment by styson** [comment]
Not much different if versions are stored in XML.

http://texas-asl.com/xml.htm

using this XML sample

http://texas-asl.com/versions.xml

```
	$.ajax({
	    type: "GET",
	    url: "versions.xml",
	    dataType: "xml",
	    success: function (xml) {
				$(xml).find('board').each(function(){
     			var id = $(this).attr("id");
     			var version = $(this).attr("version");
	        $("sub.version."+id).text("v"+version);
   			});	            
	    }
	});
```

**Comment by derimmer** [comment]
Just doing some checking and discovered that when a board is selected, ASLBoardPicker is already coded to download if missing or out-of-date. Missing boards are currently not downloaded because they do not appear in the list in the first place and so cannot be selected.  Forcing the core boards to be listed should trigger this code. See ASLBoardPicker.updateBoard( ).

**Comment by davidsullivan317** [comment]
Let's not limit the list to MMP boards. Instead include all boards in
v5boardVersions.xml
plus any local boards not in the list.

**Comment by derimmer** [comment]
Agreed in terms of the xml file. 

But only the MMP boards would be automatically added to the list the users sees in ASLBoardPicker. Other boards would be added to ASLBoardPicker only if they exist on the local drive as per current practice.

**Comment by derimmer** [comment]
I'll start by creating v5boardVersions.xml

**Comment by derimmer** [comment]
Have created v5boardVersions.xml

xml did not like two file names: B&I and Blood\u0020&\u0020Iron. It does not like the ampersand (&) in the file names. We will have to change those at some point.

**Comment by styson** [comment]
I'm sure that boards.html can get the raw version of the `v5boardVersions.xml` file from the repo, so we can do away with the json file and its upkeep.

**Comment by davidsullivan317** [comment]
I'm still not understanding why "only the MMP boards would be automatically added to the list the users sees in ASLBoardPicker" Why not add everything in the XML file to the board picker dropdown?

**Comment by zgrose** [comment]
For xml, you escape & with &amp;

`<board>B&amp;I</board>`

**Comment by derimmer** [comment]
Zoltan, good to know, thanks. 

Sully, the thinking being that users may not wish to see all the jetsam and flotsam that accumulates in the board repository. For example, given the visceral hatred that many people feel for CH products, I can only imagine the outrage if forced to see a CH board in the dropdown. Beyond the "MMP core boards" everything else should be user choice (meaning download it to see it).

I don't have strong feelings one way or another. Am coding this now as per the above but easy to include every last board if that's the way we want to go.

**Comment by Javaslinger** [comment]
Is it possible to make the dropdown into more of a expandable tree format with and MMP, BFP, and perhaps and 'others' section?  I know that's more work that a list, but it would allow you to have everything in there without it being so cluttered and also hiding the undesirables.  

I think this is a great idea by the way.  The less users have to manage in VASL, the easier it will be for new players to get on board.

**Comment by derimmer** [comment]
ASLBoardPicker.updateBoard() has some code dealing with boards whose name begins with "r" for reversed  boards. This feels like code from a long, long time ago and a place far, far way. Do we still need it or can I clean it out while working on this?

**Comment by derimmer** [comment]
I have steps 1-5 of First Steps above implemented on my local machine and it seems to be working. I have pushed the code changes up to feature/boardselectionlistissue485 if anyone wants to take a look (two separate commits). 

I think this should be tested quite broadly on other machines with different configurations and board sets. To that end, I have built a module and you can get it here as vasl-6.5.0-beta.vmod: 

https://www.dropbox.com/s/0ur2xkg7bb5r3x9/vasl-6.5.0-beta.vmod?dl=0

If you feel like give it a test drive, that would be great. Create a bunch of new games using any boards (you should get a lot of updates from bd1-79 due to Al's great work on LW); try deleting some of the core boards from your local board directory and then try to open a new game and saved game using those missing boards. 

I have not, at this point, followed Sully's suggestion to include ALL boards on the selection list automatically nor javaslinger's suggestion of the expandable tree format.

**Comment by davidsullivan317** [comment]
Works like a champ! I started with an empty directory and it grabbed the boards when selected in the board picker. 

A couple of thoughts. You have the boards broken up into "core" and "other." It might make sense to make this more granular - Core, SK, Deluxe, BFP, CH, etc. I'd still put them all in the list. What the hell. Another option would be to make the various sets selectable via preferences, but that's probably not worth it. 

It might also make sense to drop the bdFiles folder in the board folder. That would simplify the structure a bit. Also, putting the XML into the dist directory might make life more complicated for board weenies. Again, it might be simpler to have everything in one place.

**Comment by BigAl737** [comment]
This is cool! Can we do the same with the overlay extension? Jumping the gun?

**Comment by Javaslinger** [comment]
Works beautifully on my machine.  Not to harp on this, but if we can eliminate the need for users to download ANY boards, I think you take a HUGE step in improving the user each of VASL.  - Not to mention extensions...

I have no idea how difficult it would be, but if we can get the board list format into a tree format to allow inclusion of all third party boards into the list, it would be phenomenal.  You could have the MMP board section of the tree expanded by default, but have TPP boards collapsed by default.  This is Ken, btw.

**Comment by zgrose** [comment]
Not sure doing overlays would be as seamless given the way they are initialized and used.

**Comment by derimmer** [comment]
Ken, glad to hear it worked. 

Actually it is not difficult at all to apply this to all boards. In fact, it is actually simpler. 

There was some hesitation on doing so on my part for several reasons (we have less quality control over TPP boards, not many TPP boards are updated, I worried that users would not want all those boards on their machines). But what we are actually talking about is putting them all on the list. The only boards that would be downloaded would be boards that users actually click on. So, on reflection I am happy to put all boards on the list. 

So, if every board is on the list, is there a benefit in using a tree format? The tree format is not required but is it wanted?

FYI, to update the board list, all that will be necessary is to push a new version of v5boardVersions.xml to the vasl repository in Github. The next time a player opens vasl, they will get the new list in the boardpicker wizard. Which makes me realize that this only works if the player has an underlying connection to the internet (does not have to be connected via VASL). If VASL can't get the list from github, nothing will show up in the list at all. So, I will have to have vasl fail to the current method of searching the local directory if the github connection fails. Easy to do.

**Comment by styson** [comment]
I also need to update the vasl.info boards page to use the new xml file, once that is added to the repo.

**Comment by derimmer** [comment]
I have changed the code to load ALL boards into the selection list. I have also added the fail to handle users  working with no underlying internet connection. Haven't pushed changes to github yet. While I wait a couple of days for any more test results/reactions, I thought I would start thinking about overalys. So I have created a new issue #489 update overlay management and suggest that we move further discussion on overlays to that issue. This thread should continue to talk about managing boards across the repositories in github.

**Comment by Javaslinger** [comment]
My suggestion for the tree format for the board list stemmed form the concern that people would have issues with all the TPP boards showing up in the list (particularly the CH boards).  Putting the boards in the tree format would reduce the clutter and possibly make them easier to find AND keep the unwanted boards less apparent.

**Comment by derimmer** [comment]
I have pushed all the changes to the board selection process up to develop so the next time we build a VASL module, this will all be included. Note that the test module that I made available earlier will no longer work as it includes buildFile pointers that have now changed.

**Comment by styson** [comment]
vasl.info has been updated to pull version info from the XML file.

Thanks for the hard work, @derimmer!

**Comment by derimmer** [comment]
Thanks Sam. Excuses for the cross-posting but as noted in #479 I will check the version numbers in v5boardversions.xml against boards to which the LW transformation has been applied.

Also note that the xml file contains four values for each board: name, version, versionDate and description. I left all descriptions blank and used the same date for all versionDate entries. Do we make any use of version date at present? I don't think so, but if we do, I will update the values in the xml file.

**Comment by styson** [comment]
only name and version are used on the web site, so no need yet to update the date and description.

**Comment by derimmer** [comment]
At present, changes to boards/overlays/extensions still need files to be copied to all three repositories: vasl, vasl-boards-extensions, and vasl-website. 

When we release vasl-6.5.0 in the fall, we will no longer need to update vasl-boards-extensions. We will need to keep the repository in place to support users who do not move to 6.5.0 for whatever reason. And so we could continue to update it. My suggestion is that we do not. 

The impact of this would be that those users who do not upgrade to 6.5.0 would continue to have access to all board/overlay/extensions in the vasl-boards-extensions that exist at the time we release 6.5.0. And they would continue to be able to access the latest versions and new items via the website. They just wouldn't benefit from auto-syncing for new boards and versions created after 6.5.0 is released. I am ok with that? Is everyone else?

Users would be advised of this in the 6.5.0 release notice.

Over time, we should be able to do away with vasl-boards-extensions as the community moves to 6.5.0 and beyond. 

Sam, do we need to do anything to link the website to the overlay and extension files in the vasl repository rather than vasl-boards-extensions?

**Comment by derimmer** [comment]
The code changes to the board selection process that I worked on earlier this year are ready to go and I would like to roll them out to users. We have only two other code changes that I can find, both LOS related: (1) adding Light Woods and (2) fixing a bug with slopes. I am not aware of any counter fixes in the pipeline. None of the other code changes identified for 6.5.0 are ready as far as I can see.
 
Thus, I am inclined to push out VASL 6.4.3 rather than 6.5.0. 
 
I would aim for a beta release by mid-September unless anyone tells me they are working on stuff and need more time. 

Let me know if there are any changes I have missed.

**Comment by BigAl737** [comment]
Hi Doug,

I’ll have the off board hex grid overlays ready to go soon. If you don’t know about these, they are to satisfy a request made on GS. I’m gonna add these to the main map VASL overlays window, not the overlay extension. Makes more sense to put them there I think. 

Give me about a week.

Thanks.

Al

**Comment by derimmer** [comment]
> For xml, you escape & with `&amp;`
> 
> `<board>B&amp;I</board>`

@zgrose David Sullivan was doing some testing and discovered that there are several other special characters that don't seem to read well from the .xml file. For instance, 

<boarddata name="BOB\u0020DZN" version="1.0" versionDate="Aug 2008" description="" /> 

will generate an error and not load the board. 

Do you have any thoughts on how to fix this in the xml file?

There are about 10 boards with u0020 in the name. I can't find any other special characters besides this one and the & that you solved earlier.

**Comment by derimmer** [comment]
VASL6.4.3 has been released with the new board selection process. For developers, please note that there is no longer a need to update the /boards directory in the vasl-boards-extensions repository. BUT there is still a need to update the /boards/overlays directory in the same repository if adding/changing overlay files. 

In a few months, I will begin work on how to eliminate the vasl-boards-extensions repository entirely, as per the conversation above.
