### ISSUE TITLE
VASLize BFPs Corregidor Module

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#527]
This involves a HASL map and a just few counters. I have started work on this project and should have it completed soon.

My plan is to release this back to Rick as a stand alone HASL VASL map and a temporary mini extension with the counters. We can incorporate this mini extension into BFPs primary extension when Brian finishes incorporating Operation Schmidt.

I do have a question for you java coders which I'll post separately.

**Comment by derimmer** [comment]
Have a look at the RBv2 bd file and check the Boardmetadata.xml file. The A1CenterX and A1CenterY values let you decide which pixel is the A1 center dot. Given the map shown in your post, A1CenterY should be 0 + the width of the top grey band in pixels. A1CenterX should 37 + the width of the left grey band in pixels. 

This should result in counters being centered properly in the hex and chat showing correct hexes for units. If a counter looks slightly off, either left to right or up and down, adjust the A1CenterX or A1CenterY values by a pixel or two. 

None of this changes the left and top grey areas to offboard. Those grey areas will still be calculated as hexes. For example, units on the left grey area will be listed as in column -B1 or something like that. Setting the values of "width" and "height" in the Boardmetadata.xml file will set the number of hex columns and rows, respectively. This should let eliminate the right and bottom grey areas as hexes. I think you will have to include the left and top areas in the column and row count. Start by adding one to the actual number of columns and rows and see what happens.

Been a while since I played with this kind of thing, so I may be forgetting something, but that would be my best advice. Play around with the values in the Boardmetadata.xml file a bit to see what works best. Let me know if you get stuck.

**Comment by BigAl737** [comment]
Thanks Doug. Expert advice as always. I appreciate it very much.

I've been playing around with setting the number of rows and columns in the Boardmetadata.xml while it was an interesting exercise, it's not achieving what I envisioned. It'd be cool if you had the option to define a start and end x/y coordinate for each row and column. The default would remain as VASL is now but for those unique situations, you'd use the define option. It'd be a lot of inputs but it'd be worth it in situations like this.

No worries though as I have some other ideas. I know these will work and I'll post them to Rick for him to choose the best one for his VASL loving customers.

**Comment by derimmer** [comment]
Hi Al

Happy to keep working on this with you. When you say that changing the number of rows and columns isn't doing what you need, can you tell me what's missing.

VASL works with hex centers more than end x/y coordinates. In short, the A1CenterX and A1CenterY values set the center point for the A1 hex. In a geo board that is 0 and 3.25, to reflect the half width, full height nature of the A1 hex.  hexWidth and hexHeight in the Boardmetadata.xml file set the height and width of each hex (which does vary from map to map). Most Boardmetadata.xml files don't use these values and where they are absent VASL uses the standard values of 56.25 and 64.5.  Setting the number of rows and columns using width and height in the Boardmetadata.xml file then lets VASL set all the hex center points which in turn allows it to calculate which hex a given point is in. 

I am pretty sure that the right combination of these values should get you what you want. I think I have seen other maps with borders like Corregidor. 

Happy to play with the bdCorregidor file if you send it to me.

**Comment by davidsullivan317** [comment]
This might be a case where keeping the look-and-feel of the original board
may not worth the effort. Al - would you be open to moving the turn track
etc. below the map itself?

It's not possible for that grey area in the lower left that is within the
map boundary to ignore the hex grid without custom coding.

-Sully

**Comment by BigAl737** [comment]
Thx David. I don't have a problem with moving the turn track to the border. In fact, I've already done that. I just wanted to make sure that I couldn't get VASL to treat the lower left hand corner as off map. So thanks for confirming this.

Doug, I can't get VASL to treat any part of the border as off map. Here's a screen I did as a test with my Singling map.

![image](https://user-images.githubusercontent.com/10384413/51165367-73bf2a80-184c-11e9-9adb-df083253870c.png)

And this is with the rows and columns set at 1 :-) I started the test with them set at 18 and 31. It'd be nice if the turn marker wasn't constrained by snap to grid feature of the VASL hex grid. You can see VASL thinks the turn marker is in FF7 but I'd like to tell VASL that it's off board...that the map ends at column EE. If I'm understanding you correctly, it's possible for me to do this. So far though, I've failed.

I'll attach this board so you can see my settings and mess around with it. I'm curious as to what I'm doing wrong. If there is a way for VASL to treat the rectangular gray border as off map, I'd be ecstatic! But then I lead a pretty dull life :-)

[bdSGtest.zip](https://github.com/vasl-developers/vasl/files/2758481/bdSGtest.zip)

**Comment by derimmer** [comment]
After spending a pleasant Saturday afternoon tooling around on this with the Singling map that you sent me and looking at a couple of other maps (such as FB CG2) with borders, I am forced to agree with Brian and David. At present, there is no way to have the gray border area treated as offboard and be described as such in the info box that appears below the counter in your example. 

If I have understood what I have seen, the code that drives this is in VASSAL and not VASL (at least I can't find it in VASL). The border is part of the image and VASSAL is going to treat the whole image as map. 

Sorry that I led you astray on this. We can manipulate the hex grid that VASL creates in the way that you would like but that is not what drives the labelling that you see.

**Comment by BigAl737** [comment]
Thx Doug. I do have a work around that is more than acceptable in my opinion. You’ll see it in use with Corregidor if Rick agrees with me.

**Comment by BigAl737** [comment]
This is done and issued as a stand alone extension. We need to incorporate it into the main BFP extension when OS is done. Since that's a different issue, I'm closing tis one.
