### ISSUE TITLE
Classic overlay Hd2 does not appear in right hexes in one orientation

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#546]
Steps to reproduce
Create new scenario
Choose board 00
Add Overlays
Overlay Hd2, hex 1=N5, hex 2=M6
Add
Done
Ok

Expected result
Overlay Hd2 is on hexes N5 (end with opening)/M6

Actual result
Overlay Hd2 is on hexes N6 (end with opening)/M7

**Comment by derimmer** [comment]
Fixed, This was a problem in the overlay file so a new version will auto-download when required. 

I have no idea how I fixed this. I changed a value in the overlay data file and it worked. Took me a while to figure out which value and to what new value. Eventually I resorted to trial and error. 

The code that uses this value is way above my pay-grade. I have absolutely no idea how it works or why. As much as I understand it, it should not work; I cannot fathom how it does what it does. 

But the fix is in!
