### ISSUE TITLE
Board 40 Marsh to Level 0 transformation does not work

### ISSUE THREAD

**Issue by styson** [vasl-developers/vasl#599]

**Comment by bkemp01** [comment]
I think the Marsh hexes on this board need to be updated with the revised Marsh pattern and colors.

**Comment by bkemp01** [comment]
Notes:
B3,C3 - RiverMarsh
AA1 - SeparatedSwamp (next to Woods Z0)
DD3,EE4,FF3 - RiverMarsh

**Comment by bkemp01** [comment]
Lo and behold there was already a newer layered source file in the src folder with the Marsh updates already applied. (thanks to Al most likely?) I exported to a new bd40.gif and all looked correct but it still doesn't seem to behave. Also updated the colors and colorSSR files and still not working. The only Marsh hex that transforms to Level0 is AA1 which happens to be SeparatedSwamp. The other hexes are all RiverMarsh. Not sure if this is by design or not. Need to investigate further.

**Comment by bkemp01** [comment]
Still not making sense, according to the v5.9.4 colorSSR file for MarshToOpenGround...
RiverMarshGreenL0=Level0
RiverMarshBrownL0=Level0
So this should work but it doesn't.
When making the river flooded or fordable those RiverMarsh hexes turn to Water or MudflatL0 correctly.
Still stumped.

**Comment by bkemp01** [comment]
Other RiverMarsh boards exhibit this same behavior such as 07, 3a/b and 79. It may be a problem with the colorSSR file but it looks correct to me. @derimmer maybe there is a way to debug this in the code? The only way I know how to fix currently is to add a special overlay.

**Comment by bkemp01** [comment]
Thought I had found something, there were color definitions in the BoardMetadata.xml file for RiverMarshGreenL0 & RiverMarshBrownL0 set to incorrect color values. I tried both removing them and setting to current values, neither had an impact. Back to the overlay fix.

**Comment by derimmer** [comment]
I have a few days where I can look at this and the other bd problem you flagged.

**Comment by derimmer** [comment]
To be sure that I understand the problem, what is the correct behaviour we are looking for? When applying a Marsh to Level 0 transformation, we expect the marsh images to disappear and the hex to open ground at level 0? When I try that on bd40 v6.6 I don't get any changes at all, not for the River Marsh hexes nor K10 and AA1.

**Comment by bkemp01** [comment]
v6.6 does not have the updated marsh pattern and colors so it would not work at all.
[You can grab v6.7 that I was working on from my branch.](https://github.com/vasl-developers/vasl/blob/bk-bd40-marsh-fix/boards/bdFiles/bd40)
V6.7 has the updated patterns and colors.
Expected behavior is all Marsh (Green & Brown) to become Level0.
With the v6.7 board you should see K10 & AA1 change correctly.
B3,C3,DD3,EE4,FF3 do not change at all.

**Comment by derimmer** [comment]
I think I have this working properly. Here is v6.8
[bd40.zip](https://github.com/vasl-developers/vasl/files/4319171/bd40.zip)

I just added the extension .zip to the regular board. Just delete the .zip extension, don't actually unzip it. 

As far as a can see the problem was a mis-match between the various sets of colorSSRrules files that are called on during the process. The colorSSR file in the bd40 board file contained a MarshToOpenGround rule, which is perfectly valid. However, the TerrainSSR process in the Board Wizard, generates "MarshtoLevel0" as the required rule. Once I added this as a new rule to the bd40 colorSSR file, it seemed to work fine. But of course you should check it. 

If this is the problem in bd40, it is probably the problem in every board with Marsh. Also missing were the colorSSR rules MarshToLevel_1 and MarshToLevel1. These exist in the SharedBoardMetaData.xml but I am not sure all the correct colormaps are included in that file. 

This duplicity of places where colorSSR files can be fine is a recipe for inconsistencies and errors. I understand that there are good reasons for it but still. 

If my fix does work, I would suggest setting up two new issues: (1) Fix colorSSR files in all boards with Marsh terrain and  (2) Resolve inconsistencies between colorSSR files and the SharedBoardMetaData.xml file. 

The first should get early attention. The second is a longer term bit of grunt work. I am happy to work on either or both but not in the short term. 

Finally, there was a minor error in the bd40 BoardMetadata.xml file. One of the colors for the Marsh hexes was named "RiverMarshBlackL0" when it needed to be "RiverMarshBrownL0". I fixed that.

I have not pushed any files up to GitHub and will leave this in your hands. Let me know if my file does not work for you!

**Comment by bkemp01** [comment]
Thanks very much Doug. Original problem is resolved, however I did notice while going through other transforms that MarshToL_1 doesn't seem to work. It may not have worked before either. Thanks to your insight I think I can try to sort through this.

Agree that all Marsh boards need to be revisited after this is fully ironed out. I think a mass change to all boards is probably not worth the lift right now and sounds a bit risky for possibly breaking other things.

One thing that may help is understanding the order in which the various definition and rule locations are applied. Is that easily gleaned from the code?

**Comment by derimmer** [comment]
I agree with you in terms of the other boards. Let's get bd40 up and working properly and come back to the other boards later. 

In terms of the order in which definitions and rule locations are applied, yes, it can be gleaned from the code. I would not say easily, lol. Would you like me to take a shot at it?

**Comment by bkemp01** [comment]
If it's not obvious then don't bother with it yet. Let me see what I can figure out with a deeper inspection of the files.

**Comment by derimmer** [comment]
OK. If you mean the order within a file like ColorSSR then it is simple: top to bottom in the file. Same for SharedBoardMetadata.xml. If you want to know which order VASL processes ColorSSR vs SharedBoardMetadata.xml and others, then that is more complicated.

**Comment by derimmer** [comment]
I have now reviewed all boards in the vasl repo to ensure that the marsh transformation works. I have updated boards where possible. 

there are 4 boards outstanding:

bd41 and bd47 are problematic in that they have marsh hexes at both level 0 and level -1. Applying either transformation effects both marsh at both levels thus changing the level of various hexes. I will create a separate new issue for this. Deluxe bdg and bdh have marsh hexes of strange color and need some extra work to fix the transformation. I am going to ask Tom R to help on this and will create a new issue.
