### ISSUE TITLE
vasl LOS engine does not follow B19.21 for terrain IN a gully

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#629]
vasl shows LOS between 5W2 (L -1) and 5Y3 (L -1) as clear. While the LOS does not leave the gully depiction, by B19.21 the gully in hex 5X2 should be considered to have woods IN the depiction rising from level minus one. Paths within woods depictions should also considered woods, but not outside those depictions [B13.6].

Note that implementing this may be complicated by streams, because streams (even dry) *are* considered free of terrain that exists on both sides.

**Comment by derimmer** [comment]
From a rules perspective, here's one I have been playing wrong for about 35 years. I don't think the last part of 19.21 ever registered with me. Duh!

From a los engine perspective, Houston, we have a problem. Basically, Gully-coloured terrain changes terrain type depending on what else is in the hex. If there is nothing else in the hex, it is open ground. If it is woods or brush, for example, the Gully-coloured terrain is actually woods or brush for los purposes. The los engine currently treats all Gully-coloured terrain as OG. How would it know to do otherwise? We would have to create a test so that if the los engine found gully terrain it would go off and search the hex for other terrain. A bit complicated but doable. 

I might check how many such hexes exist in the core boards before starting this. Might not be worth the effort. But it is a bug.

**Comment by jrvjrv** [comment]
Applications for the rule hardly ever happen, so you may have never gotten into a situation where you misplayed it.

One possible fix would be to mark combination woods-gully hexes (metadata? Or could you scan for woods-colored pixels? I don't have the answer here) then treat the *entire* gully depiction not as level -1 OG but as a level -1 to level 0 obstacle. That wouldn't be exactly right. Only the gully depiction between the woods depictions is actually woods, and you might get some sharply-angled LOS that does not go between the woods of a particular woods-gully hex but does touch the gully part. It *might* be close enough.

Are the gully depictions encoded with level information? It might be enough to repaint the sections between woods as one level higher. Would that work? I don't know if the edge would be considered a crest line (i.e. blind hexes -1) or a regular obstacle (i.e. full blind hexes).

Another thing that would work as an image hack would be to add a "thin" strip of (level -1 to level zero) woods across the gully to join the woods on either side. That would not be something that is seen in the paper maps, but if aesthetically acceptable it would give vasl the information it needs.

**Comment by derimmer** [comment]
I have looked through the boards with LOS, a few gully-woods cases. Many more Path-Woods. Plus need to treat Brush-Gully and Brush-path as LOSH. 

Couldn't find a rule but presume the Gully-Orchards should be treated as orchard throughout (although rising to different levels within the gully depiction)?

**Comment by derimmer** [comment]
@jrvjrv Here is a link to a revised bd05. https://www.dropbox.com/s/1z49edv72nyfwnk/bd05?dl=0

 Would you mind checking it for me before I proceed more broadly? I also found applicable woods-gully hexes on boards 58 and BFP-P. In those cases, the los seemed to work as you explained that it should due to the gully configurations. I would appreciate it if you could confirm that. 

If bd05 is ok then I can fix all the other combos in the same way using the los-gui tool. It should be quite easy but a bit time-consuming so I want to be sure I am getting the rule correct before starting.

**Comment by derimmer** [comment]
Pushed up changes for all the boards that I could find where this applied. Probably missed a couple.
