### ISSUE TITLE
Slovakian 80mm Minomet vz.36 MTR Info

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#837]
VASL piece shows s7 and IR which it doesn't have. Brought up here:

http://www.gamesquad.com/forums/index.php?threads/slovakian-ordnance-show-info-error.159867/post-2041421

Verified with Slovakian Ord Note 28, pgs H154 and H157.

**Comment by derimmer** [comment]
@BigAl737 Al, I think we need to rollback this commit temporarily along with the NK one so that we return to the buildFile which uses VASSAL3.5.0-beta12 (see first line of the buildFile). That one contains changes about 15 commits that I have pushed since October of last year. 

Grab that version of the buildFile, edit it and then push it up to Github. I will not make any changes until we get this sorted. We have a pull request from a new member (@mtl1971) waiting in the wings but there is no rush there. 

I would ask that everyone else hold off on commits that change the buildFile until we get this sorted. 

It is always a risk when pushing commits that change the buildFile as it replaces the previous file entire, which is not how the code changes work. But thanks to github we can rollback and redo.

**Comment by BigAl737** [comment]
Hi Doug,

I thought I used the current build file for each of these. If I did, I don't think I changed any of your work. Does that still mess you up?

I'm not able to get on this till late tonight. Please roll back what you need and I'll redo my stuff. Please don't let me hold you up.
