### ISSUE TITLE
Phase Marker restarts after Turn 10

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#850]
From GS:

Hi,
I just played a scenario with 11 turns, and the Phase marker indicated Turn 1 when I clicked Next Phase after the last CCPh of the second player's Turn 10.
Not a dramatical issue, but perhaps could it be possible to have the marker go up to 99 turns? Or, more practically, to 29?

**Comment by BigAl737** [comment]
Got this from Steed on GS. I gave it a quick test and it works through turn 40 before starting over on 1. He says it's easy to make it go past 40 if you wanted to. Unzip it to find the extension. You'll find it in VASL under Counters-Other-Map-Mod Phase Track.

Hope this will save you some work.

[ModPhaseTrack.zip](https://github.com/vasl-developers/vasl/files/5864362/ModPhaseTrack.zip)

Here's a copy of his email:

Big Al,

Attached is the extension.  You'll find the modified Phase Tracks in COUNTERS -> OTHER -> MAP, in the list under "Mod Phase Track". 

They will go up to turn 40 ( don't know if a game will go beyond 40 turns ) but they can be modified easily to go beyond.

What I did ( after figuring out how it works ) -

Took the "Layer - TurnName" and made it Prototype called "TurnName".  I then removed the "Layer - TurnName" from each track and then added the new Prototype into each Phase  Track (in the proper order).  
In the Prototype I just added levels to the "Layer - TurnName", giving each level the proper name.
Since I was making an extension (didn't want to modify the original ones) I then had to change both Reset properties to point to the correct ( the modified ) tracks.  

After doing that I'm thinking I could just make a Prototype with a dynamic property which increments at the proper time instead of using the layer levels.  The turn count could go on indefinitely that way but when I used the dynamic property in testing, I had to change the order in which the phase was displayed.  It had to be "Turn XX Allied/Axis - phase" instead of "Allied/Axis Turn XX - phase".

Probably best to leave it the way it's been done all along.  Could always just add new levels to the layer in the prototype to increase the total turns.

I'm thinking about making a 3 player track and/or a generic track.  Have some ideas but not sure yet what is going to be possible.  

Thanks for all the work you and the other elves do - I don't think I would be playing as much as I am with VASL.

Please check it out before adding it ( if you're going to use them ) - I've tested each one and everything seems ok, but there's always something I overlook or forget.

Walt

**Comment by BigAl737** [comment]
Walt has provided an updated version that combines all four markers into one. He's making one more update as I type. When work on this issue begins again, please double check with me and I'll provide his latest work. Quite possibly he's saved us all a bunch of time.

**Comment by BigAl737** [comment]
@derimmer 

Hi Doug,

I've pushed a buildfile and added a folder to images to the CustomMarkers branch. This push adds custom turn markers to:

VASL Counters > Other > Map > Custom

To use a Phase Wheel, Turn, or Reinforcement marker, right click on the piece to open its context window. Select sides from the drop down windows. Sides set for one of the components sets it for the other two as well.

The phase wheel goes up thru turn 40 then restarts.

I modified the buildfile manually so no other changes to the build file should have occurred without my knowing.

If you would, please create a vmod build and test these changes. then if all looks well you can merge the branch into develop and delete the CustomMarkers branch.

Anytime I do anything with GitHub, I feel like I'm just barely keeping my head above water. Please let me know if I screwed something up. I already reversed one commit because I thought it was pushed to CustomMarkers but it wasn't. Hoopefully my second attempt came through okay.

Thanks Doug!

Al

**Comment by derimmer** [comment]
Hi Al

I have tested this and it works well. I like it very much. Kudos to you and Gordon. 

I had to make a small change to the buildFile so I will look after pushing it all into develop.
