### ISSUE TITLE
Develop using Java 16?

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#904]
@uckelman I see that VASSAL3.5.5 enables the use of Java 16. Would you recommend that we switch to it in our development environment? At present I am using JDK1.8.0.

**Comment by uckelman** [comment]
You're targeting Java 11 according to your `pom.xml`---which is what you should be targeting--- and Java 8 can't produce class files compatible with Java 11, so I'm certain you're not using Java 8 for Maven builds.

You can use any version of Java you want from 11 onward for doing builds, as any version from 11 onward will be able to target 11.

To be clear: VASSAL is not building Java 16 class files, only bundling Java 16 with our Windows and Mac packages. Java 11 will remain the baseline for class files for quite a while, since there are many, many long-term-support Linux distros where Java 11 is the newest Java which is packaged for them.

**Comment by derimmer** [comment]
OK. Thanks. Yes, I am targeting Java 11. I just have shit for brains and don't understand what I am looking at.
