### ISSUE TITLE
Counter bug causing VASSAL crash

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#905]
There are a number of bugs reported to VASSAL that are all caused by the same code:

2021-03-14 14:07:41,184 [1226-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog - Image not found: sv238H
2021-03-14 14:07:41,208 [1226-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog - Image not found: svqmark58
2021-03-14 14:07:41,209 [1226-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog - Image not found: svqmark58
2021-03-14 14:07:42,044 [1226-AWT-EventQueue-0] ERROR VASSAL.tools.ErrorDialog - 
java.lang.IllegalArgumentException: Width (-1) and height (-1) must be > 0
	at java.desktop/java.awt.image.SampleModel.<init>(SampleModel.java:126)
	at java.desktop/java.awt.image.ComponentSampleModel.<init>(ComponentSampleModel.java:140)
	at java.desktop/java.awt.image.PixelInterleavedSampleModel.<init>(PixelInterleavedSampleModel.java:87)
	at java.desktop/java.awt.image.Raster.createInterleavedRaster(Raster.java:642)
	at java.desktop/java.awt.image.Raster.createInterleavedRaster(Raster.java:278)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:391)
	at VASL.counters.Concealable.loadImages(Concealable.java:311)
	at VASL.counters.Concealable.drawObscuredToMe(Concealable.java:87)

The problem appears to be caused by the Swedish extension not being loaded. 

For most counters this results in a Warning message which does not cause a crash. But in the case of concealment counters, VASL.counters.Concealable.loadImages() tries to create a generic counter and this part of the method is not working this instance.

The key part of loadImages() is as follows: 

if (concealedToOthers == null) {
      try {
        concealedToOthers = Op.load(nation + "/" + nation + "qmarkme.gif").getImage(null);
      }
      catch (Exception ex) {
        // Using generic qmarkme.gif image and prefs-specified colors
        int size = imageSize.width;
        BufferedImage rev = new BufferedImage(size, size, BufferedImage.TYPE_4BYTE_ABGR);
        Graphics2D g = rev.createGraphics();
        g.drawString("?", 0, 0);
        concealedToOthers = rev;
      }

The crash is being caused by  BufferedImage rev = new BufferedImage(size, size, BufferedImage.TYPE_4BYTE_ABGR); when size is not greater than 0.

My thought is to test for the value of size before this line and exit if not >0. Or I could try to adjust the previous part of loadImages() to ensure that size is always >0. 

I am loath to touch any of the code dealing with concealment as I find it very hard to decipher (due to my ignorance not the code itself). 

Any ideas as to the best way to fix this?

**Comment by zgrose** [comment]
So when the nation is `fu` and there is no concealment counter for `fu` this code tries to throw a generic ?. It might be safer to do this:
* create a generic white ? counter in the main module
* when an exception is thrown loading a nation specific ? counter, just load that system generic one.

````
if (concealedToOthers == null) {
try {
concealedToOthers = Op.load(nation + "/" + nation + "qmarkme.gif").getImage(null);
}
catch (Exception ex) {
// Could not find a nation-specific concealment counter, use the system default
concealedToOthers = Op.load("sys/sysqmarkme.gif").getImage(null);
}
````

If that throws an exception, things are probably super broken anyway. (Making a sys folder is optional, I just kept the same pattern of nation/nationqmarkme.gif

Now they'll have white ? counters over missing (?) nationality counters since they didn't have the required extension loaded and it should be obvious something is wrong.

You might also want to drop a message in the chat window that they are missing an extension to support the `nation` counters.

**Comment by zgrose** [comment]
If you want to go the minimal route (since half their scenario isn't going to load anyway), I concur that
````
if (concealedToOthers == null) {
  try {
    concealedToOthers = Op.load(nation + "/" + nation + "qmarkme.gif").getImage(null);
  }
  catch (Exception ex) {
    // Using generic qmarkme.gif image and prefs-specified colors
    int size = imageSize.width;
    if (size > 0) {
      BufferedImage rev = new BufferedImage(size, size, BufferedImage.TYPE_4BYTE_ABGR);
      Graphics2D g = rev.createGraphics();
      g.drawString("?", 0, 0);
      concealedToOthers = rev;
  }
}
````

should suppress the exception, but I imagine exiting this code block such that `concealedToOthers` equals `null` is just going to throw an Exception somewhere else, so I won't go that route, personally.

**Comment by uckelman** [comment]
* This is further down but, catching anything in `Concealable.drawObscuredToMe()` is wrong. Nothing it calls should throw, and if anything it calls does throw unexpectedly, you want that to propagate so there's a bug report as a result. (This goes also for `Concealable.drawObscuredToOthers()`.)

* Catching `Exception` in `loadImages()` is also wrong, in both places. Nothing there should throw, either. (Basically everywhere in VASL that someone is catching `Exception`, whoever wrote that code didn't understand what they were doing and they tried to sweep a problem they didn't understand under the rug.)

* `Op.load()` should not be wrapped in a `try` intended to catch exceptions thrown from it. It is not declared to throw any exceptions. Any exceptions it does throw are due to bugs, so if you catch those, we'll never be able to find and fix them.

* The immediate problem is that you're reaching line 310 without ever having set `imageSize.width` with a real width.

**Comment by uckelman** [comment]
Exiting if you get to line 310 and `imageSize.with < 0` totally defeats the purpose of that block of code, btw. The block that's in is intended to produce an image as a fallback in case you weren't able to load an image to use.

If you want it to match the case for when `concealedToMe` fails to load, try setting the size to 20 x 20.

And just check if `concealedToOthers` is null, rather than catching `Exception`.

```
concealedToOthers = Op.load(nation + "/" + nation + "qmarkme.gif").getImage();
if (concealedToOthers == null) {
  // Using generic qmarkme.gif image and prefs-specified colors
  concealedToOthers = new BufferedImage(20, 20, BufferedImage.TYPE_4BYTE_ABGR);
  final Graphics2D g = concealedToOthers.createGraphics();
  g.drawString("?", 0, 0);
  g.dispose();
}
```

**Comment by derimmer** [comment]
I have been able to resolve the problem with the above code (one tweak needed) and will push this change up to develop. I will look at the .draw. . . methods separately.

**Comment by derimmer** [comment]
> * This is further down, but catching anything in `Concealable.drawObscuredToMe()` is wrong. Nothing it calls should throw, and if anything it calls does throw unexpectedly, you want that to propagate so there's a bug report as a result. (This goes also for `Concealable.drawObscuredToOthers()`.)
> * Catching `Exception` in `loadImages()` is also wrong, in both places. Nothing there should throw, either. (Basically everywhere in VASL that someone is catching `Exception`, whoever wrote that code didn't understand what they were doing and they tried to sweep a problem they didn't understand under the rug. There are only a few, very specific cases in which catching Exception is the right thing to do, and I've seen nowhere in VASL where those cases occur.)
> * `Op.load().getImage()` should not be wrapped in a `try` intended to catch exceptions thrown from it. It is not declared to throw any exceptions. Any exceptions it does throw are due to bugs, so if you catch those, we'll never be able to find and fix them.

I have removed the try . . catch from each of these 3 specific situations. Will test this is my dev build for a while before pushing up.

**Comment by derimmer** [comment]
@uckelman @zgrose Thanks for your comments. Both of you helped me see what was going on here and what to do about it.

**Comment by derimmer** [comment]
@uckelman if I can impose on you for some further advice 

Further to your comments about the inappropriate use of Exception in VASL code, the following is an example of one usage from LOS.Map.Map.java(528):

public boolean hexOnMap(int col, int row) {

        try {
            Hex temp = hexGrid[col][row];
            return true; 
        }
        catch (Exception e) {

            return false;
        }
    }

This is used to determine if a particular "hex" is on the map. The hex can have col and row values that are outside the bounds of the hexGrid.  Those bounds are highly variable and unpredictable due to different map configurations. 

How should I be thinking about rewriting such code?

**Comment by zgrose** [comment]
One option:
````
public boolean hexOnMap(int col, int row) {
    // can't assume hexGrid isn't null, probably worth letting the NPE get thrown if it is?
    if (hexGrid.length == 0) return false; // when there are no columns, nothing can be in the map
    if ((col < 0) || (row < 0)) return false;   // negative rows/columns are off the map by definition?
    return ((col < hexGrid.length) && (row < hexGrid[0].length));
}
`````

The idea is to test:
- if `hexGrid` has any elements at all in the first array,
- if `col` or `row` is negative, can never be on the map (true?)
- if `col` and `row` are values within the upper limit of the arrays

Didn't slap into the code to test all the bits, but I think the concepts are solid.

**Comment by uckelman** [comment]
The simplest and most performant thing you can do for the body of that function is this:
```
return col >= 0 && col < hexGrid.length && row >= 0 && row < hexGrid[col].length;
```

**Comment by derimmer** [comment]
Duh! My brain would not conceive of hexGrid.length of hexGrid[col].length! Easy solution. I will plug it in and see if it works. 

Thanks to you both for quick and helpful replies.
