### ISSUE TITLE
Mark Moved Bug

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#911]
FRom GS:

While setting up my units, I turn off the "Mark units moved" option. When I moved a Russian vehicle, however, VASL flagged it as moved. VASL did not flag Russian infantry.

**Comment by mtl1971** [comment]
There is a simple 'fix' / workaround to this problem that could be applied in code in [MarkMoved.java](https://github.com/vasl-developers/vasl/blob/develop/src/VASL/counters/MarkMoved.java) 
Add a PropertyChangeListener to the class:
`    String markMovedKey = "markMoved";
    Prefs gameModulePrefs = GameModule.getGameModule().getPrefs();
    markMovedConfigurer = (BooleanConfigurer)gameModulePrefs.getOption(markMovedKey);
    if (markMovedConfigurer != null) {
      shouldMarkMoved = markMovedConfigurer.booleanValue();
      markMovedConfigurer.addPropertyChangeListener(e -> {
        shouldMarkMoved = (boolean) e.getNewValue();
      });
    }`

then inspect the state of shouldMarkMoved whenever something is marked as moved, and if disabled, don't.

But this seems to be hiding the underlying problem rather than addressing it. Am I right in thinking that this behaviour should be governed by VASSAL using attributes set on the GamePieces rather than managed in VASL itself? If so, does anyone know why we have a MarkMoved class in VASL?

**Comment by uckelman** [comment]
VASSAL has the MovementMarkable trait which does this. I can't answer why VASL does something different.

**Comment by derimmer** [comment]
This problem got worse before it got better as the VASSAL showMarkedMove preference disappeared for a bit. It is now back. 

Thanks to @uckelman and @Cattlesquat over at VASSAL HQ, I have been able to re-attach VASL's MarkMoved class to this preference and I think we are back to the functionality we want. It will be in 667.

**Comment by Cattlesquat** [comment]
Whew! :)
