### ISSUE TITLE
SS Assault Engineers and Assault Fire

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#991]
FRom GS:

The 5-4-8 SS AE and 8-3-8 SS AE are missing their "SS" symbol, although they appear correct in every other respect. Maybe not a huge deal, but if you had a scenario featuring Wehrmacht 8-3-8 AE and SS 8-3-8 AE the only way you could distinguish them would be to flip them to their broken side. It would probably be better to replace the "AE" with the little DC symbol as used on the physical counters and keep the SS symbol on those squad types.

However the 2-3-8 SS AE HS derived from the 5-4-8 SS AE squad are missing the underlined morale (but again, otherwise appear correct).

The "SS" tab under the "HS" tab is missing the 2-3-8 SS AE counter, so you can't "pull" them at will; you have to pull a full squad and turn it into a HS.

**Comment by derimmer** [comment]
See also http://www.gamesquad.com/forums/index.php?threads/ss-assault-fire.188149/#post-2140013

SS 468 and 447 squads lack the Assault Fire option found on the 658.

**Comment by apbills** [comment]
Created new images for 838/338 and 548/238 AE units using the DC image and the SS logo.
Added in the functionality for 44+ assault fire on the 468 and 447 counters - the image was already present in the vmod.  Not sure about the missing 238AE counter since it was there in beta5.  Note that both the German and the Waffen SS nationality trays were updated.
